syntax = "proto3";

package system_proto;
option go_package = "./;system";
import "github.com/gogo/protobuf/gogoproto/gogo.proto";
import "github.com/gly-hub/quickgo/grpcep/lib.proto";
import "user.proto";
import "role.proto";

message LoginReq {
  string username = 1 [(gogoproto.jsontag) = 'username'];
  string password = 2 [(gogoproto.jsontag) = 'password'];
}

message LoginResp {
  grpcep.CommonResp common_resp = 1 [(gogoproto.jsontag) = 'common_resp'];
  User user = 2 [(gogoproto.jsontag) = 'user'];
  repeated Role roles = 3 [(gogoproto.jsontag) = 'roles'];
  reserved 4, 5;
  reserved "token", "expiresIn";
  string access_token = 6 [(gogoproto.jsontag) = 'accessToken'];
  string refresh_token = 7 [(gogoproto.jsontag) = 'refreshToken'];
  int64 access_expires_in = 8 [(gogoproto.jsontag) = 'accessExpiresIn'];
  int64 refresh_expires_in = 9 [(gogoproto.jsontag) = 'refreshExpiresIn'];
}

message RefreshTokenReq {
  string refresh_token = 1 [(gogoproto.jsontag) = 'refreshToken'];
}

message RefreshTokenResp {
  grpcep.CommonResp common_resp = 1 [(gogoproto.jsontag) = 'common_resp'];
  User user = 2 [(gogoproto.jsontag) = 'user'];
  repeated Role roles = 3 [(gogoproto.jsontag) = 'roles'];
  string access_token = 4 [(gogoproto.jsontag) = 'accessToken'];
  string refresh_token = 5 [(gogoproto.jsontag) = 'refreshToken'];
  int64 access_expires_in = 6 [(gogoproto.jsontag) = 'accessExpiresIn'];
  int64 refresh_expires_in = 7 [(gogoproto.jsontag) = 'refreshExpiresIn'];
}

message LogoutReq {
  string refresh_token = 1 [(gogoproto.jsontag) = 'refreshToken'];
}

message LogoutResp {
  grpcep.CommonResp common_resp = 1 [(gogoproto.jsontag) = 'common_resp'];
}

message ValidateTokenReq {
  string token = 1 [(gogoproto.jsontag) = 'token'];
}

message ValidateTokenResp {
  grpcep.CommonResp common_resp = 1 [(gogoproto.jsontag) = 'common_resp'];
  User user = 2 [(gogoproto.jsontag) = 'user'];
  repeated Role roles = 3 [(gogoproto.jsontag) = 'roles'];
}
