// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: system-service.proto

package system

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("system-service.proto", fileDescriptor_78cdb519d6e05a0b) }

var fileDescriptor_78cdb519d6e05a0b = []byte{
	// 1048 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x97, 0x41, 0x6f, 0xdc, 0x44,
	0x14, 0xc7, 0x93, 0x03, 0x91, 0x3a, 0xb4, 0x40, 0xa7, 0x85, 0x96, 0x4d, 0x77, 0xdb, 0x26, 0xa2,
	0xd0, 0x22, 0x82, 0x04, 0x17, 0xa4, 0x9e, 0x4a, 0x42, 0x56, 0xa0, 0x4d, 0xa9, 0xd6, 0x4d, 0x25,
	0x10, 0x52, 0xe4, 0xee, 0xbe, 0x6c, 0xac, 0x7a, 0x67, 0x26, 0x1e, 0x3b, 0x55, 0xbf, 0x05, 0x1f,
	0x8b, 0x63, 0x8f, 0x1c, 0x51, 0x72, 0xe5, 0x43, 0xa0, 0xf1, 0xb3, 0x3d, 0xe3, 0xf1, 0x1b, 0xef,
	0x4a, 0xdc, 0x76, 0xdf, 0xff, 0xbf, 0xbf, 0x79, 0x3b, 0xfe, 0x3f, 0x7b, 0xcc, 0x6e, 0xeb, 0x77,
	0x3a, 0x87, 0xe5, 0x37, 0x1a, 0xb2, 0x8b, 0x64, 0x06, 0x7b, 0x2a, 0x93, 0xb9, 0xe4, 0x5b, 0x58,
	0x1d, 0xb0, 0x42, 0x43, 0x86, 0xb5, 0x01, 0x5b, 0x82, 0x28, 0xea, 0xcf, 0x99, 0x4c, 0xa1, 0xfe,
	0x1c, 0x17, 0xf9, 0x59, 0xf5, 0xf9, 0x66, 0xbc, 0x00, 0x91, 0x9f, 0x2c, 0xe5, 0x1c, 0xd2, 0xaa,
	0xc4, 0xb1, 0x34, 0x93, 0xe2, 0x34, 0x59, 0x54, 0xb5, 0x5b, 0x52, 0x41, 0x16, 0xe7, 0x89, 0x14,
	0x27, 0xa9, 0xac, 0x8b, 0x5c, 0xc8, 0x3c, 0x39, 0x4d, 0x66, 0x65, 0xbd, 0xaa, 0x5d, 0x2f, 0x54,
	0x2a, 0xe3, 0x39, 0x7e, 0xfb, 0xee, 0xdf, 0x1d, 0x76, 0x23, 0x2a, 0x1b, 0x8b, 0xb0, 0x5b, 0xfe,
	0x03, 0xfb, 0x60, 0x22, 0x17, 0x89, 0xe0, 0x9f, 0xed, 0x61, 0xc7, 0x27, 0xa5, 0x73, 0xaf, 0x2c,
	0x4e, 0xe1, 0x7c, 0x70, 0x87, 0xac, 0x6b, 0xc5, 0x8f, 0xd8, 0xf5, 0x29, 0x9c, 0x66, 0xa0, 0xcf,
	0x5e, 0xca, 0x37, 0x20, 0xf8, 0xb0, 0x6d, 0x74, 0x35, 0xc3, 0x19, 0xf5, 0xc9, 0x5a, 0xf1, 0xa7,
	0x6c, 0x6b, 0x22, 0x17, 0xb2, 0xc8, 0x79, 0x77, 0x45, 0x59, 0xe4, 0x06, 0x71, 0x97, 0x16, 0xb4,
	0xe2, 0x2f, 0xd8, 0x8d, 0x57, 0x71, 0x9a, 0xcc, 0xe3, 0x1c, 0xb0, 0x19, 0x6f, 0xb5, 0x96, 0x68,
	0x50, 0xf7, 0x7b, 0x75, 0xad, 0xf8, 0x01, 0xbb, 0x36, 0x49, 0x74, 0x7e, 0xac, 0x21, 0xd3, 0x7c,
	0xe0, 0x2d, 0x5c, 0x0b, 0x86, 0xb4, 0x1d, 0xd4, 0xb4, 0xe2, 0x63, 0xc6, 0xf6, 0x33, 0x88, 0x73,
	0x30, 0x25, 0xee, 0x59, 0xad, 0x62, 0x38, 0xf7, 0xc2, 0x22, 0x82, 0x8e, 0xd5, 0x3c, 0x00, 0xb2,
	0x0a, 0x01, 0x72, 0x45, 0x04, 0x1d, 0x40, 0x0a, 0x34, 0xc8, 0x2a, 0x04, 0xc8, 0x15, 0x11, 0xf4,
	0x93, 0x88, 0x5f, 0xa7, 0x24, 0xc8, 0x2a, 0x04, 0xc8, 0x15, 0xb5, 0xe2, 0xbf, 0xb0, 0x0f, 0x0f,
	0x12, 0xdd, 0x90, 0xfc, 0x55, 0xad, 0x64, 0x50, 0xc3, 0x1e, 0x15, 0x33, 0x39, 0x86, 0x72, 0xff,
	0xa7, 0x32, 0x05, 0xed, 0x67, 0xd2, 0xd5, 0x88, 0x4c, 0xb6, 0x65, 0xc4, 0x45, 0x3d, 0xb8, 0xa8,
	0x1f, 0x17, 0xf9, 0xb8, 0x2a, 0x53, 0xc8, 0x22, 0x32, 0xd5, 0x80, 0xb6, 0x83, 0x9a, 0x9b, 0x29,
	0x53, 0xa2, 0x33, 0x65, 0x94, 0x60, 0xa6, 0x50, 0x74, 0x33, 0x45, 0x81, 0xac, 0x12, 0xcc, 0x94,
	0x0b, 0xc2, 0x70, 0x50, 0x20, 0xab, 0x04, 0x33, 0xe5, 0x82, 0x30, 0x1c, 0x14, 0xc8, 0x2a, 0xc1,
	0x4c, 0x35, 0x20, 0x9b, 0xa9, 0x92, 0x44, 0x67, 0xaa, 0x46, 0x0d, 0x7b, 0xd4, 0x26, 0x53, 0xe6,
	0xeb, 0x11, 0x88, 0x82, 0xca, 0x54, 0xa3, 0xd1, 0x99, 0x72, 0xe4, 0x26, 0x53, 0x41, 0x5c, 0xd4,
	0x8f, 0x8b, 0x7c, 0x5c, 0x95, 0x29, 0x64, 0x11, 0x99, 0x6a, 0x40, 0xdb, 0x41, 0x0d, 0xf7, 0x6b,
	0x0c, 0xf9, 0xf3, 0xf8, 0x02, 0x39, 0xf7, 0x3a, 0xff, 0xa1, 0x96, 0x88, 0xfd, 0x6a, 0xa9, 0x6e,
	0x3e, 0x4d, 0x89, 0xce, 0xa7, 0x51, 0x82, 0xf9, 0x44, 0xd1, 0xcd, 0x27, 0x05, 0xb2, 0x4a, 0x30,
	0x9f, 0x2e, 0x08, 0x83, 0x46, 0x81, 0xac, 0x12, 0xcc, 0xa7, 0x0b, 0xc2, 0xa0, 0x51, 0x20, 0xab,
	0x04, 0xf3, 0xd9, 0x80, 0x6c, 0x3e, 0x4b, 0x12, 0x9d, 0xcf, 0x1a, 0x35, 0xec, 0x51, 0xb5, 0xe2,
	0x39, 0xfb, 0x3c, 0x7a, 0x27, 0x66, 0x63, 0x10, 0xe6, 0x44, 0x00, 0xf3, 0xc3, 0x42, 0xcc, 0xcc,
	0x01, 0xa0, 0x24, 0x3f, 0xf1, 0xe2, 0x13, 0x32, 0x9a, 0x75, 0xbe, 0x5e, 0xdb, 0xab, 0x15, 0x17,
	0xec, 0xce, 0xfe, 0x19, 0xcc, 0xde, 0xb8, 0xc2, 0xb3, 0xd9, 0x0c, 0xb4, 0xe6, 0x5f, 0x79, 0x57,
	0x95, 0xb6, 0x99, 0x15, 0x1f, 0xaf, 0xe9, 0xd4, 0x8a, 0xbf, 0x62, 0x1f, 0x97, 0xb2, 0xb3, 0xce,
	0x03, 0xe2, 0xd7, 0x6d, 0xfe, 0xc3, 0x15, 0x0e, 0xe4, 0x9a, 0x51, 0x78, 0x66, 0x8e, 0x58, 0x47,
	0xe6, 0xd0, 0xd5, 0xe1, 0x7a, 0x32, 0xc1, 0xed, 0x38, 0xb4, 0xe2, 0xc0, 0x6e, 0x8f, 0xc1, 0xa9,
	0x4e, 0x0b, 0x91, 0x27, 0x4b, 0xe0, 0x5f, 0x74, 0x86, 0xa7, 0xe3, 0x31, 0x2b, 0x3c, 0x5a, 0xc7,
	0xa6, 0x15, 0xff, 0x8d, 0x7d, 0x82, 0x53, 0x63, 0x65, 0xfe, 0x90, 0x9a, 0x2a, 0xe7, 0xe7, 0x70,
	0x3e, 0xd8, 0x59, 0x65, 0x41, 0x34, 0xce, 0x51, 0x18, 0xed, 0xeb, 0x04, 0xba, 0x6b, 0x41, 0x34,
	0x4e, 0x56, 0x18, 0xed, 0xeb, 0x04, 0xba, 0x6b, 0x41, 0x34, 0xce, 0x5a, 0x18, 0xed, 0xeb, 0x04,
	0xba, 0x6b, 0xd1, 0x8a, 0xff, 0xc1, 0x6e, 0x56, 0xb3, 0xe7, 0xb0, 0x77, 0xc8, 0xe1, 0x6c, 0xc3,
	0x77, 0x57, 0x7a, 0xb4, 0xe2, 0x11, 0xfb, 0xa8, 0xbe, 0xca, 0xfb, 0xe5, 0x49, 0x9f, 0xdf, 0xa7,
	0x33, 0x80, 0xaa, 0xe1, 0x3e, 0xe8, 0x37, 0x60, 0xcb, 0xce, 0x05, 0xa8, 0xb8, 0xe1, 0x2b, 0x64,
	0xd1, 0xbb, 0x2b, 0x3d, 0x78, 0x0f, 0x68, 0xa2, 0x1f, 0x81, 0xd6, 0x89, 0x14, 0xa8, 0x76, 0xee,
	0x01, 0x01, 0x1b, 0x71, 0x0f, 0x08, 0x3a, 0xb5, 0xe2, 0xe7, 0xec, 0xae, 0xd3, 0x48, 0xcb, 0xc0,
	0x1f, 0x07, 0x1b, 0x6e, 0xf9, 0xcc, 0x8a, 0x4f, 0xd6, 0xb5, 0xe2, 0x06, 0x9a, 0x8e, 0x7e, 0xad,
	0xdf, 0xb6, 0x26, 0x72, 0xa1, 0xfd, 0x0d, 0xec, 0x18, 0x88, 0x0d, 0x24, 0x3c, 0x96, 0xfe, 0xdc,
	0x79, 0x6d, 0x23, 0xe9, 0x2d, 0x43, 0x80, 0xee, 0x79, 0x70, 0x14, 0x22, 0x10, 0x73, 0x57, 0xf0,
	0x47, 0xc1, 0xd7, 0x89, 0x51, 0xe8, 0x5a, 0x10, 0x3d, 0x85, 0xb8, 0x17, 0xed, 0xeb, 0x04, 0xba,
	0x6b, 0xc1, 0xf3, 0x51, 0xf5, 0xee, 0x53, 0xbe, 0xb8, 0xfa, 0xe7, 0x23, 0x57, 0x23, 0xce, 0x47,
	0x6d, 0x19, 0x3b, 0x35, 0xc7, 0xfa, 0xb2, 0xf0, 0x22, 0xce, 0xf2, 0xe3, 0xe9, 0xc4, 0xef, 0xd4,
	0xd7, 0x89, 0x4e, 0xbb, 0x16, 0x9c, 0xd8, 0x7d, 0xb9, 0x54, 0xe5, 0x5b, 0x11, 0xf6, 0xea, 0x4d,
	0x6c, 0x5b, 0x25, 0x26, 0xd6, 0x37, 0x68, 0xc5, 0x5f, 0xb2, 0x5b, 0x76, 0xb1, 0x0c, 0x2e, 0x12,
	0x78, 0x6b, 0x5a, 0x1e, 0x06, 0xfa, 0xa9, 0xda, 0x1d, 0xf5, 0xc9, 0x5a, 0xf1, 0xe3, 0xf2, 0x69,
	0x84, 0xb5, 0x03, 0xf9, 0x56, 0x54, 0xda, 0xff, 0xc5, 0x9e, 0xb1, 0x4f, 0xa7, 0xa0, 0x65, 0x7a,
	0x51, 0xfd, 0x83, 0x43, 0x99, 0x95, 0x73, 0xc4, 0x1f, 0xf9, 0x17, 0x9a, 0x30, 0x99, 0x05, 0xbe,
	0x5c, 0xcb, 0x57, 0x3f, 0x8c, 0x70, 0x93, 0x96, 0x32, 0x87, 0xc3, 0x24, 0x85, 0xee, 0xc3, 0xa8,
	0xad, 0x93, 0x0f, 0x23, 0xdf, 0xe2, 0xa2, 0x7f, 0x16, 0x69, 0x22, 0x7a, 0xd0, 0x56, 0x0f, 0xa2,
	0x5d, 0x8b, 0x56, 0x3f, 0xee, 0xfe, 0x75, 0x39, 0xda, 0x7c, 0x7f, 0x39, 0xda, 0xfc, 0xe7, 0x72,
	0xb4, 0xf9, 0xe7, 0xd5, 0x68, 0xe3, 0xfd, 0xd5, 0x68, 0xe3, 0xef, 0xab, 0xd1, 0xc6, 0xef, 0xd7,
	0xf6, 0xbe, 0x7d, 0x8a, 0xbf, 0x7f, 0xbd, 0x55, 0x02, 0xbe, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x23, 0x56, 0xcf, 0xa9, 0x48, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SystemServiceClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error)
	Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error)
	ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error)
	ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error)
	CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
	UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserResp, error)
	DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error)
	EnableUser(ctx context.Context, in *EnableUserReq, opts ...grpc.CallOption) (*EnableUserResp, error)
	DisableUser(ctx context.Context, in *DisableUserReq, opts ...grpc.CallOption) (*DisableUserResp, error)
	GetUserRoles(ctx context.Context, in *GetUserRolesReq, opts ...grpc.CallOption) (*GetUserRolesResp, error)
	SetUserRoles(ctx context.Context, in *SetUserRolesReq, opts ...grpc.CallOption) (*SetUserRolesResp, error)
	ListRoles(ctx context.Context, in *ListRolesReq, opts ...grpc.CallOption) (*ListRolesResp, error)
	CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleResp, error)
	UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error)
	DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*DeleteRoleResp, error)
	EnableRole(ctx context.Context, in *EnableRoleReq, opts ...grpc.CallOption) (*EnableRoleResp, error)
	DisableRole(ctx context.Context, in *DisableRoleReq, opts ...grpc.CallOption) (*DisableRoleResp, error)
	GetRoleMenus(ctx context.Context, in *GetRoleMenusReq, opts ...grpc.CallOption) (*GetRoleMenusResp, error)
	SetRoleMenus(ctx context.Context, in *SetRoleMenusReq, opts ...grpc.CallOption) (*SetRoleMenusResp, error)
	ListMenus(ctx context.Context, in *ListMenusReq, opts ...grpc.CallOption) (*ListMenusResp, error)
	GetNavMenus(ctx context.Context, in *GetNavMenusReq, opts ...grpc.CallOption) (*GetNavMenusResp, error)
	CreateMenu(ctx context.Context, in *CreateMenuReq, opts ...grpc.CallOption) (*CreateMenuResp, error)
	UpdateMenu(ctx context.Context, in *UpdateMenuReq, opts ...grpc.CallOption) (*UpdateMenuResp, error)
	DeleteMenu(ctx context.Context, in *DeleteMenuReq, opts ...grpc.CallOption) (*DeleteMenuResp, error)
	EnableMenu(ctx context.Context, in *EnableMenuReq, opts ...grpc.CallOption) (*EnableMenuResp, error)
	DisableMenu(ctx context.Context, in *DisableMenuReq, opts ...grpc.CallOption) (*DisableMenuResp, error)
	SyncGeneratedFunctionMenu(ctx context.Context, in *SyncGeneratedFunctionMenuReq, opts ...grpc.CallOption) (*SyncGeneratedFunctionMenuResp, error)
	CheckFunctionMenuAccess(ctx context.Context, in *CheckFunctionMenuAccessReq, opts ...grpc.CallOption) (*CheckFunctionMenuAccessResp, error)
	CheckMenuAccess(ctx context.Context, in *CheckMenuAccessReq, opts ...grpc.CallOption) (*CheckMenuAccessResp, error)
	ListAgentModels(ctx context.Context, in *ListAgentModelsReq, opts ...grpc.CallOption) (*ListAgentModelsResp, error)
	GetAgentModelRuntime(ctx context.Context, in *GetAgentModelRuntimeReq, opts ...grpc.CallOption) (*GetAgentModelRuntimeResp, error)
	CreateAgentModel(ctx context.Context, in *CreateAgentModelReq, opts ...grpc.CallOption) (*CreateAgentModelResp, error)
	UpdateAgentModel(ctx context.Context, in *UpdateAgentModelReq, opts ...grpc.CallOption) (*UpdateAgentModelResp, error)
	DeleteAgentModel(ctx context.Context, in *DeleteAgentModelReq, opts ...grpc.CallOption) (*DeleteAgentModelResp, error)
	EnableAgentModel(ctx context.Context, in *EnableAgentModelReq, opts ...grpc.CallOption) (*EnableAgentModelResp, error)
	DisableAgentModel(ctx context.Context, in *DisableAgentModelReq, opts ...grpc.CallOption) (*DisableAgentModelResp, error)
	GetAgentConfig(ctx context.Context, in *GetAgentConfigReq, opts ...grpc.CallOption) (*GetAgentConfigResp, error)
	UpdateAgentConfig(ctx context.Context, in *UpdateAgentConfigReq, opts ...grpc.CallOption) (*UpdateAgentConfigResp, error)
	ListAgentSessionConfigs(ctx context.Context, in *ListAgentSessionConfigsReq, opts ...grpc.CallOption) (*ListAgentSessionConfigsResp, error)
	UpdateAgentSessionConfig(ctx context.Context, in *UpdateAgentSessionConfigReq, opts ...grpc.CallOption) (*UpdateAgentSessionConfigResp, error)
	ListOperationLogs(ctx context.Context, in *ListOperationLogsReq, opts ...grpc.CallOption) (*ListOperationLogsResp, error)
	ListNotifications(ctx context.Context, in *ListNotificationsReq, opts ...grpc.CallOption) (*ListNotificationsResp, error)
	SendNotification(ctx context.Context, in *SendNotificationReq, opts ...grpc.CallOption) (*SendNotificationResp, error)
	ReadNotification(ctx context.Context, in *ReadNotificationReq, opts ...grpc.CallOption) (*ReadNotificationResp, error)
	CreateUpload(ctx context.Context, in *CreateUploadReq, opts ...grpc.CallOption) (*CreateUploadResp, error)
	GetUploadPartURL(ctx context.Context, in *GetUploadPartURLReq, opts ...grpc.CallOption) (*GetUploadPartURLResp, error)
	CompleteUpload(ctx context.Context, in *CompleteUploadReq, opts ...grpc.CallOption) (*CompleteUploadResp, error)
	GetUploadPreviewURL(ctx context.Context, in *GetUploadURLReq, opts ...grpc.CallOption) (*GetUploadURLResp, error)
	GetUploadDownloadURL(ctx context.Context, in *GetUploadURLReq, opts ...grpc.CallOption) (*GetUploadURLResp, error)
	ResolveUploadForAgent(ctx context.Context, in *ResolveUploadForAgentReq, opts ...grpc.CallOption) (*ResolveUploadForAgentResp, error)
	UploadRemoteFile(ctx context.Context, in *UploadRemoteFileReq, opts ...grpc.CallOption) (*UploadRemoteFileResp, error)
	UploadInlineFile(ctx context.Context, in *UploadInlineFileReq, opts ...grpc.CallOption) (*UploadInlineFileResp, error)
}

type systemServiceClient struct {
	cc *grpc.ClientConn
}

func NewSystemServiceClient(cc *grpc.ClientConn) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenResp, error) {
	out := new(RefreshTokenResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResp, error) {
	out := new(LogoutResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenReq, opts ...grpc.CallOption) (*ValidateTokenResp, error) {
	out := new(ValidateTokenResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListUsers(ctx context.Context, in *ListUsersReq, opts ...grpc.CallOption) (*ListUsersResp, error) {
	out := new(ListUsersResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	out := new(CreateUserResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserResp, error) {
	out := new(UpdateUserResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResp, error) {
	out := new(DeleteUserResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) EnableUser(ctx context.Context, in *EnableUserReq, opts ...grpc.CallOption) (*EnableUserResp, error) {
	out := new(EnableUserResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/EnableUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) DisableUser(ctx context.Context, in *DisableUserReq, opts ...grpc.CallOption) (*DisableUserResp, error) {
	out := new(DisableUserResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/DisableUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetUserRoles(ctx context.Context, in *GetUserRolesReq, opts ...grpc.CallOption) (*GetUserRolesResp, error) {
	out := new(GetUserRolesResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/GetUserRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) SetUserRoles(ctx context.Context, in *SetUserRolesReq, opts ...grpc.CallOption) (*SetUserRolesResp, error) {
	out := new(SetUserRolesResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/SetUserRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListRoles(ctx context.Context, in *ListRolesReq, opts ...grpc.CallOption) (*ListRolesResp, error) {
	out := new(ListRolesResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/ListRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) CreateRole(ctx context.Context, in *CreateRoleReq, opts ...grpc.CallOption) (*CreateRoleResp, error) {
	out := new(CreateRoleResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/CreateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) UpdateRole(ctx context.Context, in *UpdateRoleReq, opts ...grpc.CallOption) (*UpdateRoleResp, error) {
	out := new(UpdateRoleResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/UpdateRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) DeleteRole(ctx context.Context, in *DeleteRoleReq, opts ...grpc.CallOption) (*DeleteRoleResp, error) {
	out := new(DeleteRoleResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/DeleteRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) EnableRole(ctx context.Context, in *EnableRoleReq, opts ...grpc.CallOption) (*EnableRoleResp, error) {
	out := new(EnableRoleResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/EnableRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) DisableRole(ctx context.Context, in *DisableRoleReq, opts ...grpc.CallOption) (*DisableRoleResp, error) {
	out := new(DisableRoleResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/DisableRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetRoleMenus(ctx context.Context, in *GetRoleMenusReq, opts ...grpc.CallOption) (*GetRoleMenusResp, error) {
	out := new(GetRoleMenusResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/GetRoleMenus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) SetRoleMenus(ctx context.Context, in *SetRoleMenusReq, opts ...grpc.CallOption) (*SetRoleMenusResp, error) {
	out := new(SetRoleMenusResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/SetRoleMenus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListMenus(ctx context.Context, in *ListMenusReq, opts ...grpc.CallOption) (*ListMenusResp, error) {
	out := new(ListMenusResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/ListMenus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetNavMenus(ctx context.Context, in *GetNavMenusReq, opts ...grpc.CallOption) (*GetNavMenusResp, error) {
	out := new(GetNavMenusResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/GetNavMenus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) CreateMenu(ctx context.Context, in *CreateMenuReq, opts ...grpc.CallOption) (*CreateMenuResp, error) {
	out := new(CreateMenuResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/CreateMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) UpdateMenu(ctx context.Context, in *UpdateMenuReq, opts ...grpc.CallOption) (*UpdateMenuResp, error) {
	out := new(UpdateMenuResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/UpdateMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) DeleteMenu(ctx context.Context, in *DeleteMenuReq, opts ...grpc.CallOption) (*DeleteMenuResp, error) {
	out := new(DeleteMenuResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/DeleteMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) EnableMenu(ctx context.Context, in *EnableMenuReq, opts ...grpc.CallOption) (*EnableMenuResp, error) {
	out := new(EnableMenuResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/EnableMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) DisableMenu(ctx context.Context, in *DisableMenuReq, opts ...grpc.CallOption) (*DisableMenuResp, error) {
	out := new(DisableMenuResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/DisableMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) SyncGeneratedFunctionMenu(ctx context.Context, in *SyncGeneratedFunctionMenuReq, opts ...grpc.CallOption) (*SyncGeneratedFunctionMenuResp, error) {
	out := new(SyncGeneratedFunctionMenuResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/SyncGeneratedFunctionMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) CheckFunctionMenuAccess(ctx context.Context, in *CheckFunctionMenuAccessReq, opts ...grpc.CallOption) (*CheckFunctionMenuAccessResp, error) {
	out := new(CheckFunctionMenuAccessResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/CheckFunctionMenuAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) CheckMenuAccess(ctx context.Context, in *CheckMenuAccessReq, opts ...grpc.CallOption) (*CheckMenuAccessResp, error) {
	out := new(CheckMenuAccessResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/CheckMenuAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListAgentModels(ctx context.Context, in *ListAgentModelsReq, opts ...grpc.CallOption) (*ListAgentModelsResp, error) {
	out := new(ListAgentModelsResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/ListAgentModels", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetAgentModelRuntime(ctx context.Context, in *GetAgentModelRuntimeReq, opts ...grpc.CallOption) (*GetAgentModelRuntimeResp, error) {
	out := new(GetAgentModelRuntimeResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/GetAgentModelRuntime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) CreateAgentModel(ctx context.Context, in *CreateAgentModelReq, opts ...grpc.CallOption) (*CreateAgentModelResp, error) {
	out := new(CreateAgentModelResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/CreateAgentModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) UpdateAgentModel(ctx context.Context, in *UpdateAgentModelReq, opts ...grpc.CallOption) (*UpdateAgentModelResp, error) {
	out := new(UpdateAgentModelResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/UpdateAgentModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) DeleteAgentModel(ctx context.Context, in *DeleteAgentModelReq, opts ...grpc.CallOption) (*DeleteAgentModelResp, error) {
	out := new(DeleteAgentModelResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/DeleteAgentModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) EnableAgentModel(ctx context.Context, in *EnableAgentModelReq, opts ...grpc.CallOption) (*EnableAgentModelResp, error) {
	out := new(EnableAgentModelResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/EnableAgentModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) DisableAgentModel(ctx context.Context, in *DisableAgentModelReq, opts ...grpc.CallOption) (*DisableAgentModelResp, error) {
	out := new(DisableAgentModelResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/DisableAgentModel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetAgentConfig(ctx context.Context, in *GetAgentConfigReq, opts ...grpc.CallOption) (*GetAgentConfigResp, error) {
	out := new(GetAgentConfigResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/GetAgentConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) UpdateAgentConfig(ctx context.Context, in *UpdateAgentConfigReq, opts ...grpc.CallOption) (*UpdateAgentConfigResp, error) {
	out := new(UpdateAgentConfigResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/UpdateAgentConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListAgentSessionConfigs(ctx context.Context, in *ListAgentSessionConfigsReq, opts ...grpc.CallOption) (*ListAgentSessionConfigsResp, error) {
	out := new(ListAgentSessionConfigsResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/ListAgentSessionConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) UpdateAgentSessionConfig(ctx context.Context, in *UpdateAgentSessionConfigReq, opts ...grpc.CallOption) (*UpdateAgentSessionConfigResp, error) {
	out := new(UpdateAgentSessionConfigResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/UpdateAgentSessionConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListOperationLogs(ctx context.Context, in *ListOperationLogsReq, opts ...grpc.CallOption) (*ListOperationLogsResp, error) {
	out := new(ListOperationLogsResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/ListOperationLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ListNotifications(ctx context.Context, in *ListNotificationsReq, opts ...grpc.CallOption) (*ListNotificationsResp, error) {
	out := new(ListNotificationsResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/ListNotifications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) SendNotification(ctx context.Context, in *SendNotificationReq, opts ...grpc.CallOption) (*SendNotificationResp, error) {
	out := new(SendNotificationResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/SendNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ReadNotification(ctx context.Context, in *ReadNotificationReq, opts ...grpc.CallOption) (*ReadNotificationResp, error) {
	out := new(ReadNotificationResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/ReadNotification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) CreateUpload(ctx context.Context, in *CreateUploadReq, opts ...grpc.CallOption) (*CreateUploadResp, error) {
	out := new(CreateUploadResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/CreateUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetUploadPartURL(ctx context.Context, in *GetUploadPartURLReq, opts ...grpc.CallOption) (*GetUploadPartURLResp, error) {
	out := new(GetUploadPartURLResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/GetUploadPartURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) CompleteUpload(ctx context.Context, in *CompleteUploadReq, opts ...grpc.CallOption) (*CompleteUploadResp, error) {
	out := new(CompleteUploadResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/CompleteUpload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetUploadPreviewURL(ctx context.Context, in *GetUploadURLReq, opts ...grpc.CallOption) (*GetUploadURLResp, error) {
	out := new(GetUploadURLResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/GetUploadPreviewURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) GetUploadDownloadURL(ctx context.Context, in *GetUploadURLReq, opts ...grpc.CallOption) (*GetUploadURLResp, error) {
	out := new(GetUploadURLResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/GetUploadDownloadURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) ResolveUploadForAgent(ctx context.Context, in *ResolveUploadForAgentReq, opts ...grpc.CallOption) (*ResolveUploadForAgentResp, error) {
	out := new(ResolveUploadForAgentResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/ResolveUploadForAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) UploadRemoteFile(ctx context.Context, in *UploadRemoteFileReq, opts ...grpc.CallOption) (*UploadRemoteFileResp, error) {
	out := new(UploadRemoteFileResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/UploadRemoteFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) UploadInlineFile(ctx context.Context, in *UploadInlineFileReq, opts ...grpc.CallOption) (*UploadInlineFileResp, error) {
	out := new(UploadInlineFileResp)
	err := c.cc.Invoke(ctx, "/system.SystemService/UploadInlineFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
type SystemServiceServer interface {
	Login(context.Context, *LoginReq) (*LoginResp, error)
	RefreshToken(context.Context, *RefreshTokenReq) (*RefreshTokenResp, error)
	Logout(context.Context, *LogoutReq) (*LogoutResp, error)
	ValidateToken(context.Context, *ValidateTokenReq) (*ValidateTokenResp, error)
	ListUsers(context.Context, *ListUsersReq) (*ListUsersResp, error)
	CreateUser(context.Context, *CreateUserReq) (*CreateUserResp, error)
	UpdateUser(context.Context, *UpdateUserReq) (*UpdateUserResp, error)
	DeleteUser(context.Context, *DeleteUserReq) (*DeleteUserResp, error)
	EnableUser(context.Context, *EnableUserReq) (*EnableUserResp, error)
	DisableUser(context.Context, *DisableUserReq) (*DisableUserResp, error)
	GetUserRoles(context.Context, *GetUserRolesReq) (*GetUserRolesResp, error)
	SetUserRoles(context.Context, *SetUserRolesReq) (*SetUserRolesResp, error)
	ListRoles(context.Context, *ListRolesReq) (*ListRolesResp, error)
	CreateRole(context.Context, *CreateRoleReq) (*CreateRoleResp, error)
	UpdateRole(context.Context, *UpdateRoleReq) (*UpdateRoleResp, error)
	DeleteRole(context.Context, *DeleteRoleReq) (*DeleteRoleResp, error)
	EnableRole(context.Context, *EnableRoleReq) (*EnableRoleResp, error)
	DisableRole(context.Context, *DisableRoleReq) (*DisableRoleResp, error)
	GetRoleMenus(context.Context, *GetRoleMenusReq) (*GetRoleMenusResp, error)
	SetRoleMenus(context.Context, *SetRoleMenusReq) (*SetRoleMenusResp, error)
	ListMenus(context.Context, *ListMenusReq) (*ListMenusResp, error)
	GetNavMenus(context.Context, *GetNavMenusReq) (*GetNavMenusResp, error)
	CreateMenu(context.Context, *CreateMenuReq) (*CreateMenuResp, error)
	UpdateMenu(context.Context, *UpdateMenuReq) (*UpdateMenuResp, error)
	DeleteMenu(context.Context, *DeleteMenuReq) (*DeleteMenuResp, error)
	EnableMenu(context.Context, *EnableMenuReq) (*EnableMenuResp, error)
	DisableMenu(context.Context, *DisableMenuReq) (*DisableMenuResp, error)
	SyncGeneratedFunctionMenu(context.Context, *SyncGeneratedFunctionMenuReq) (*SyncGeneratedFunctionMenuResp, error)
	CheckFunctionMenuAccess(context.Context, *CheckFunctionMenuAccessReq) (*CheckFunctionMenuAccessResp, error)
	CheckMenuAccess(context.Context, *CheckMenuAccessReq) (*CheckMenuAccessResp, error)
	ListAgentModels(context.Context, *ListAgentModelsReq) (*ListAgentModelsResp, error)
	GetAgentModelRuntime(context.Context, *GetAgentModelRuntimeReq) (*GetAgentModelRuntimeResp, error)
	CreateAgentModel(context.Context, *CreateAgentModelReq) (*CreateAgentModelResp, error)
	UpdateAgentModel(context.Context, *UpdateAgentModelReq) (*UpdateAgentModelResp, error)
	DeleteAgentModel(context.Context, *DeleteAgentModelReq) (*DeleteAgentModelResp, error)
	EnableAgentModel(context.Context, *EnableAgentModelReq) (*EnableAgentModelResp, error)
	DisableAgentModel(context.Context, *DisableAgentModelReq) (*DisableAgentModelResp, error)
	GetAgentConfig(context.Context, *GetAgentConfigReq) (*GetAgentConfigResp, error)
	UpdateAgentConfig(context.Context, *UpdateAgentConfigReq) (*UpdateAgentConfigResp, error)
	ListAgentSessionConfigs(context.Context, *ListAgentSessionConfigsReq) (*ListAgentSessionConfigsResp, error)
	UpdateAgentSessionConfig(context.Context, *UpdateAgentSessionConfigReq) (*UpdateAgentSessionConfigResp, error)
	ListOperationLogs(context.Context, *ListOperationLogsReq) (*ListOperationLogsResp, error)
	ListNotifications(context.Context, *ListNotificationsReq) (*ListNotificationsResp, error)
	SendNotification(context.Context, *SendNotificationReq) (*SendNotificationResp, error)
	ReadNotification(context.Context, *ReadNotificationReq) (*ReadNotificationResp, error)
	CreateUpload(context.Context, *CreateUploadReq) (*CreateUploadResp, error)
	GetUploadPartURL(context.Context, *GetUploadPartURLReq) (*GetUploadPartURLResp, error)
	CompleteUpload(context.Context, *CompleteUploadReq) (*CompleteUploadResp, error)
	GetUploadPreviewURL(context.Context, *GetUploadURLReq) (*GetUploadURLResp, error)
	GetUploadDownloadURL(context.Context, *GetUploadURLReq) (*GetUploadURLResp, error)
	ResolveUploadForAgent(context.Context, *ResolveUploadForAgentReq) (*ResolveUploadForAgentResp, error)
	UploadRemoteFile(context.Context, *UploadRemoteFileReq) (*UploadRemoteFileResp, error)
	UploadInlineFile(context.Context, *UploadInlineFileReq) (*UploadInlineFileResp, error)
}

// UnimplementedSystemServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSystemServiceServer struct {
}

func (*UnimplementedSystemServiceServer) Login(ctx context.Context, req *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedSystemServiceServer) RefreshToken(ctx context.Context, req *RefreshTokenReq) (*RefreshTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (*UnimplementedSystemServiceServer) Logout(ctx context.Context, req *LogoutReq) (*LogoutResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedSystemServiceServer) ValidateToken(ctx context.Context, req *ValidateTokenReq) (*ValidateTokenResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}
func (*UnimplementedSystemServiceServer) ListUsers(ctx context.Context, req *ListUsersReq) (*ListUsersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (*UnimplementedSystemServiceServer) CreateUser(ctx context.Context, req *CreateUserReq) (*CreateUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedSystemServiceServer) UpdateUser(ctx context.Context, req *UpdateUserReq) (*UpdateUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedSystemServiceServer) DeleteUser(ctx context.Context, req *DeleteUserReq) (*DeleteUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedSystemServiceServer) EnableUser(ctx context.Context, req *EnableUserReq) (*EnableUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableUser not implemented")
}
func (*UnimplementedSystemServiceServer) DisableUser(ctx context.Context, req *DisableUserReq) (*DisableUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableUser not implemented")
}
func (*UnimplementedSystemServiceServer) GetUserRoles(ctx context.Context, req *GetUserRolesReq) (*GetUserRolesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRoles not implemented")
}
func (*UnimplementedSystemServiceServer) SetUserRoles(ctx context.Context, req *SetUserRolesReq) (*SetUserRolesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserRoles not implemented")
}
func (*UnimplementedSystemServiceServer) ListRoles(ctx context.Context, req *ListRolesReq) (*ListRolesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoles not implemented")
}
func (*UnimplementedSystemServiceServer) CreateRole(ctx context.Context, req *CreateRoleReq) (*CreateRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRole not implemented")
}
func (*UnimplementedSystemServiceServer) UpdateRole(ctx context.Context, req *UpdateRoleReq) (*UpdateRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRole not implemented")
}
func (*UnimplementedSystemServiceServer) DeleteRole(ctx context.Context, req *DeleteRoleReq) (*DeleteRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRole not implemented")
}
func (*UnimplementedSystemServiceServer) EnableRole(ctx context.Context, req *EnableRoleReq) (*EnableRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableRole not implemented")
}
func (*UnimplementedSystemServiceServer) DisableRole(ctx context.Context, req *DisableRoleReq) (*DisableRoleResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableRole not implemented")
}
func (*UnimplementedSystemServiceServer) GetRoleMenus(ctx context.Context, req *GetRoleMenusReq) (*GetRoleMenusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoleMenus not implemented")
}
func (*UnimplementedSystemServiceServer) SetRoleMenus(ctx context.Context, req *SetRoleMenusReq) (*SetRoleMenusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRoleMenus not implemented")
}
func (*UnimplementedSystemServiceServer) ListMenus(ctx context.Context, req *ListMenusReq) (*ListMenusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMenus not implemented")
}
func (*UnimplementedSystemServiceServer) GetNavMenus(ctx context.Context, req *GetNavMenusReq) (*GetNavMenusResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNavMenus not implemented")
}
func (*UnimplementedSystemServiceServer) CreateMenu(ctx context.Context, req *CreateMenuReq) (*CreateMenuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMenu not implemented")
}
func (*UnimplementedSystemServiceServer) UpdateMenu(ctx context.Context, req *UpdateMenuReq) (*UpdateMenuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMenu not implemented")
}
func (*UnimplementedSystemServiceServer) DeleteMenu(ctx context.Context, req *DeleteMenuReq) (*DeleteMenuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMenu not implemented")
}
func (*UnimplementedSystemServiceServer) EnableMenu(ctx context.Context, req *EnableMenuReq) (*EnableMenuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableMenu not implemented")
}
func (*UnimplementedSystemServiceServer) DisableMenu(ctx context.Context, req *DisableMenuReq) (*DisableMenuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableMenu not implemented")
}
func (*UnimplementedSystemServiceServer) SyncGeneratedFunctionMenu(ctx context.Context, req *SyncGeneratedFunctionMenuReq) (*SyncGeneratedFunctionMenuResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncGeneratedFunctionMenu not implemented")
}
func (*UnimplementedSystemServiceServer) CheckFunctionMenuAccess(ctx context.Context, req *CheckFunctionMenuAccessReq) (*CheckFunctionMenuAccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckFunctionMenuAccess not implemented")
}
func (*UnimplementedSystemServiceServer) CheckMenuAccess(ctx context.Context, req *CheckMenuAccessReq) (*CheckMenuAccessResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckMenuAccess not implemented")
}
func (*UnimplementedSystemServiceServer) ListAgentModels(ctx context.Context, req *ListAgentModelsReq) (*ListAgentModelsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgentModels not implemented")
}
func (*UnimplementedSystemServiceServer) GetAgentModelRuntime(ctx context.Context, req *GetAgentModelRuntimeReq) (*GetAgentModelRuntimeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentModelRuntime not implemented")
}
func (*UnimplementedSystemServiceServer) CreateAgentModel(ctx context.Context, req *CreateAgentModelReq) (*CreateAgentModelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgentModel not implemented")
}
func (*UnimplementedSystemServiceServer) UpdateAgentModel(ctx context.Context, req *UpdateAgentModelReq) (*UpdateAgentModelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgentModel not implemented")
}
func (*UnimplementedSystemServiceServer) DeleteAgentModel(ctx context.Context, req *DeleteAgentModelReq) (*DeleteAgentModelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAgentModel not implemented")
}
func (*UnimplementedSystemServiceServer) EnableAgentModel(ctx context.Context, req *EnableAgentModelReq) (*EnableAgentModelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableAgentModel not implemented")
}
func (*UnimplementedSystemServiceServer) DisableAgentModel(ctx context.Context, req *DisableAgentModelReq) (*DisableAgentModelResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableAgentModel not implemented")
}
func (*UnimplementedSystemServiceServer) GetAgentConfig(ctx context.Context, req *GetAgentConfigReq) (*GetAgentConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentConfig not implemented")
}
func (*UnimplementedSystemServiceServer) UpdateAgentConfig(ctx context.Context, req *UpdateAgentConfigReq) (*UpdateAgentConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgentConfig not implemented")
}
func (*UnimplementedSystemServiceServer) ListAgentSessionConfigs(ctx context.Context, req *ListAgentSessionConfigsReq) (*ListAgentSessionConfigsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAgentSessionConfigs not implemented")
}
func (*UnimplementedSystemServiceServer) UpdateAgentSessionConfig(ctx context.Context, req *UpdateAgentSessionConfigReq) (*UpdateAgentSessionConfigResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAgentSessionConfig not implemented")
}
func (*UnimplementedSystemServiceServer) ListOperationLogs(ctx context.Context, req *ListOperationLogsReq) (*ListOperationLogsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOperationLogs not implemented")
}
func (*UnimplementedSystemServiceServer) ListNotifications(ctx context.Context, req *ListNotificationsReq) (*ListNotificationsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotifications not implemented")
}
func (*UnimplementedSystemServiceServer) SendNotification(ctx context.Context, req *SendNotificationReq) (*SendNotificationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNotification not implemented")
}
func (*UnimplementedSystemServiceServer) ReadNotification(ctx context.Context, req *ReadNotificationReq) (*ReadNotificationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadNotification not implemented")
}
func (*UnimplementedSystemServiceServer) CreateUpload(ctx context.Context, req *CreateUploadReq) (*CreateUploadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUpload not implemented")
}
func (*UnimplementedSystemServiceServer) GetUploadPartURL(ctx context.Context, req *GetUploadPartURLReq) (*GetUploadPartURLResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadPartURL not implemented")
}
func (*UnimplementedSystemServiceServer) CompleteUpload(ctx context.Context, req *CompleteUploadReq) (*CompleteUploadResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteUpload not implemented")
}
func (*UnimplementedSystemServiceServer) GetUploadPreviewURL(ctx context.Context, req *GetUploadURLReq) (*GetUploadURLResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadPreviewURL not implemented")
}
func (*UnimplementedSystemServiceServer) GetUploadDownloadURL(ctx context.Context, req *GetUploadURLReq) (*GetUploadURLResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUploadDownloadURL not implemented")
}
func (*UnimplementedSystemServiceServer) ResolveUploadForAgent(ctx context.Context, req *ResolveUploadForAgentReq) (*ResolveUploadForAgentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveUploadForAgent not implemented")
}
func (*UnimplementedSystemServiceServer) UploadRemoteFile(ctx context.Context, req *UploadRemoteFileReq) (*UploadRemoteFileResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadRemoteFile not implemented")
}
func (*UnimplementedSystemServiceServer) UploadInlineFile(ctx context.Context, req *UploadInlineFileReq) (*UploadInlineFileResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadInlineFile not implemented")
}

func RegisterSystemServiceServer(s *grpc.Server, srv SystemServiceServer) {
	s.RegisterService(&_SystemService_serviceDesc, srv)
}

func _SystemService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).RefreshToken(ctx, req.(*RefreshTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).Logout(ctx, req.(*LogoutReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ValidateToken(ctx, req.(*ValidateTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListUsers(ctx, req.(*ListUsersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).CreateUser(ctx, req.(*CreateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).UpdateUser(ctx, req.(*UpdateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).DeleteUser(ctx, req.(*DeleteUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_EnableUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).EnableUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/EnableUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).EnableUser(ctx, req.(*EnableUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_DisableUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).DisableUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/DisableUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).DisableUser(ctx, req.(*DisableUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/GetUserRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetUserRoles(ctx, req.(*GetUserRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_SetUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).SetUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/SetUserRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).SetUserRoles(ctx, req.(*SetUserRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/ListRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListRoles(ctx, req.(*ListRolesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_CreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).CreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/CreateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).CreateRole(ctx, req.(*CreateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_UpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).UpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/UpdateRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).UpdateRole(ctx, req.(*UpdateRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_DeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).DeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/DeleteRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).DeleteRole(ctx, req.(*DeleteRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_EnableRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).EnableRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/EnableRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).EnableRole(ctx, req.(*EnableRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_DisableRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableRoleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).DisableRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/DisableRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).DisableRole(ctx, req.(*DisableRoleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetRoleMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoleMenusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetRoleMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/GetRoleMenus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetRoleMenus(ctx, req.(*GetRoleMenusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_SetRoleMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoleMenusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).SetRoleMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/SetRoleMenus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).SetRoleMenus(ctx, req.(*SetRoleMenusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMenusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/ListMenus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListMenus(ctx, req.(*ListMenusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetNavMenus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNavMenusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetNavMenus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/GetNavMenus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetNavMenus(ctx, req.(*GetNavMenusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_CreateMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).CreateMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/CreateMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).CreateMenu(ctx, req.(*CreateMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_UpdateMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).UpdateMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/UpdateMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).UpdateMenu(ctx, req.(*UpdateMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_DeleteMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).DeleteMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/DeleteMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).DeleteMenu(ctx, req.(*DeleteMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_EnableMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).EnableMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/EnableMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).EnableMenu(ctx, req.(*EnableMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_DisableMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).DisableMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/DisableMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).DisableMenu(ctx, req.(*DisableMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_SyncGeneratedFunctionMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncGeneratedFunctionMenuReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).SyncGeneratedFunctionMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/SyncGeneratedFunctionMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).SyncGeneratedFunctionMenu(ctx, req.(*SyncGeneratedFunctionMenuReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_CheckFunctionMenuAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFunctionMenuAccessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).CheckFunctionMenuAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/CheckFunctionMenuAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).CheckFunctionMenuAccess(ctx, req.(*CheckFunctionMenuAccessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_CheckMenuAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckMenuAccessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).CheckMenuAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/CheckMenuAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).CheckMenuAccess(ctx, req.(*CheckMenuAccessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListAgentModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentModelsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListAgentModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/ListAgentModels",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListAgentModels(ctx, req.(*ListAgentModelsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetAgentModelRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentModelRuntimeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetAgentModelRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/GetAgentModelRuntime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetAgentModelRuntime(ctx, req.(*GetAgentModelRuntimeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_CreateAgentModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentModelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).CreateAgentModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/CreateAgentModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).CreateAgentModel(ctx, req.(*CreateAgentModelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_UpdateAgentModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentModelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).UpdateAgentModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/UpdateAgentModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).UpdateAgentModel(ctx, req.(*UpdateAgentModelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_DeleteAgentModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentModelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).DeleteAgentModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/DeleteAgentModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).DeleteAgentModel(ctx, req.(*DeleteAgentModelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_EnableAgentModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableAgentModelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).EnableAgentModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/EnableAgentModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).EnableAgentModel(ctx, req.(*EnableAgentModelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_DisableAgentModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableAgentModelReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).DisableAgentModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/DisableAgentModel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).DisableAgentModel(ctx, req.(*DisableAgentModelReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetAgentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetAgentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/GetAgentConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetAgentConfig(ctx, req.(*GetAgentConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_UpdateAgentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).UpdateAgentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/UpdateAgentConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).UpdateAgentConfig(ctx, req.(*UpdateAgentConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListAgentSessionConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentSessionConfigsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListAgentSessionConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/ListAgentSessionConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListAgentSessionConfigs(ctx, req.(*ListAgentSessionConfigsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_UpdateAgentSessionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentSessionConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).UpdateAgentSessionConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/UpdateAgentSessionConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).UpdateAgentSessionConfig(ctx, req.(*UpdateAgentSessionConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListOperationLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperationLogsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListOperationLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/ListOperationLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListOperationLogs(ctx, req.(*ListOperationLogsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ListNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ListNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/ListNotifications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ListNotifications(ctx, req.(*ListNotificationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/SendNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).SendNotification(ctx, req.(*SendNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ReadNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ReadNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/ReadNotification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ReadNotification(ctx, req.(*ReadNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_CreateUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).CreateUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/CreateUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).CreateUpload(ctx, req.(*CreateUploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetUploadPartURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadPartURLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetUploadPartURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/GetUploadPartURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetUploadPartURL(ctx, req.(*GetUploadPartURLReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_CompleteUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).CompleteUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/CompleteUpload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).CompleteUpload(ctx, req.(*CompleteUploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetUploadPreviewURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadURLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetUploadPreviewURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/GetUploadPreviewURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetUploadPreviewURL(ctx, req.(*GetUploadURLReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_GetUploadDownloadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadURLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetUploadDownloadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/GetUploadDownloadURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetUploadDownloadURL(ctx, req.(*GetUploadURLReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_ResolveUploadForAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveUploadForAgentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).ResolveUploadForAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/ResolveUploadForAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).ResolveUploadForAgent(ctx, req.(*ResolveUploadForAgentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_UploadRemoteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadRemoteFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).UploadRemoteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/UploadRemoteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).UploadRemoteFile(ctx, req.(*UploadRemoteFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_UploadInlineFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadInlineFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).UploadInlineFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.SystemService/UploadInlineFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).UploadInlineFile(ctx, req.(*UploadInlineFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _SystemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "system.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _SystemService_Login_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _SystemService_RefreshToken_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _SystemService_Logout_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _SystemService_ValidateToken_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _SystemService_ListUsers_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _SystemService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _SystemService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _SystemService_DeleteUser_Handler,
		},
		{
			MethodName: "EnableUser",
			Handler:    _SystemService_EnableUser_Handler,
		},
		{
			MethodName: "DisableUser",
			Handler:    _SystemService_DisableUser_Handler,
		},
		{
			MethodName: "GetUserRoles",
			Handler:    _SystemService_GetUserRoles_Handler,
		},
		{
			MethodName: "SetUserRoles",
			Handler:    _SystemService_SetUserRoles_Handler,
		},
		{
			MethodName: "ListRoles",
			Handler:    _SystemService_ListRoles_Handler,
		},
		{
			MethodName: "CreateRole",
			Handler:    _SystemService_CreateRole_Handler,
		},
		{
			MethodName: "UpdateRole",
			Handler:    _SystemService_UpdateRole_Handler,
		},
		{
			MethodName: "DeleteRole",
			Handler:    _SystemService_DeleteRole_Handler,
		},
		{
			MethodName: "EnableRole",
			Handler:    _SystemService_EnableRole_Handler,
		},
		{
			MethodName: "DisableRole",
			Handler:    _SystemService_DisableRole_Handler,
		},
		{
			MethodName: "GetRoleMenus",
			Handler:    _SystemService_GetRoleMenus_Handler,
		},
		{
			MethodName: "SetRoleMenus",
			Handler:    _SystemService_SetRoleMenus_Handler,
		},
		{
			MethodName: "ListMenus",
			Handler:    _SystemService_ListMenus_Handler,
		},
		{
			MethodName: "GetNavMenus",
			Handler:    _SystemService_GetNavMenus_Handler,
		},
		{
			MethodName: "CreateMenu",
			Handler:    _SystemService_CreateMenu_Handler,
		},
		{
			MethodName: "UpdateMenu",
			Handler:    _SystemService_UpdateMenu_Handler,
		},
		{
			MethodName: "DeleteMenu",
			Handler:    _SystemService_DeleteMenu_Handler,
		},
		{
			MethodName: "EnableMenu",
			Handler:    _SystemService_EnableMenu_Handler,
		},
		{
			MethodName: "DisableMenu",
			Handler:    _SystemService_DisableMenu_Handler,
		},
		{
			MethodName: "SyncGeneratedFunctionMenu",
			Handler:    _SystemService_SyncGeneratedFunctionMenu_Handler,
		},
		{
			MethodName: "CheckFunctionMenuAccess",
			Handler:    _SystemService_CheckFunctionMenuAccess_Handler,
		},
		{
			MethodName: "CheckMenuAccess",
			Handler:    _SystemService_CheckMenuAccess_Handler,
		},
		{
			MethodName: "ListAgentModels",
			Handler:    _SystemService_ListAgentModels_Handler,
		},
		{
			MethodName: "GetAgentModelRuntime",
			Handler:    _SystemService_GetAgentModelRuntime_Handler,
		},
		{
			MethodName: "CreateAgentModel",
			Handler:    _SystemService_CreateAgentModel_Handler,
		},
		{
			MethodName: "UpdateAgentModel",
			Handler:    _SystemService_UpdateAgentModel_Handler,
		},
		{
			MethodName: "DeleteAgentModel",
			Handler:    _SystemService_DeleteAgentModel_Handler,
		},
		{
			MethodName: "EnableAgentModel",
			Handler:    _SystemService_EnableAgentModel_Handler,
		},
		{
			MethodName: "DisableAgentModel",
			Handler:    _SystemService_DisableAgentModel_Handler,
		},
		{
			MethodName: "GetAgentConfig",
			Handler:    _SystemService_GetAgentConfig_Handler,
		},
		{
			MethodName: "UpdateAgentConfig",
			Handler:    _SystemService_UpdateAgentConfig_Handler,
		},
		{
			MethodName: "ListAgentSessionConfigs",
			Handler:    _SystemService_ListAgentSessionConfigs_Handler,
		},
		{
			MethodName: "UpdateAgentSessionConfig",
			Handler:    _SystemService_UpdateAgentSessionConfig_Handler,
		},
		{
			MethodName: "ListOperationLogs",
			Handler:    _SystemService_ListOperationLogs_Handler,
		},
		{
			MethodName: "ListNotifications",
			Handler:    _SystemService_ListNotifications_Handler,
		},
		{
			MethodName: "SendNotification",
			Handler:    _SystemService_SendNotification_Handler,
		},
		{
			MethodName: "ReadNotification",
			Handler:    _SystemService_ReadNotification_Handler,
		},
		{
			MethodName: "CreateUpload",
			Handler:    _SystemService_CreateUpload_Handler,
		},
		{
			MethodName: "GetUploadPartURL",
			Handler:    _SystemService_GetUploadPartURL_Handler,
		},
		{
			MethodName: "CompleteUpload",
			Handler:    _SystemService_CompleteUpload_Handler,
		},
		{
			MethodName: "GetUploadPreviewURL",
			Handler:    _SystemService_GetUploadPreviewURL_Handler,
		},
		{
			MethodName: "GetUploadDownloadURL",
			Handler:    _SystemService_GetUploadDownloadURL_Handler,
		},
		{
			MethodName: "ResolveUploadForAgent",
			Handler:    _SystemService_ResolveUploadForAgent_Handler,
		},
		{
			MethodName: "UploadRemoteFile",
			Handler:    _SystemService_UploadRemoteFile_Handler,
		},
		{
			MethodName: "UploadInlineFile",
			Handler:    _SystemService_UploadInlineFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system-service.proto",
}
