// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: upload.proto

package system

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpcep "github.com/gly-hub/quickgo/grpcep"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UploadSession struct {
	Uuid           string  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
	UploadId       string  `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"uploadId"`
	Mode           string  `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode"`
	Url            string  `protobuf:"bytes,4,opt,name=url,proto3" json:"url"`
	ContentType    string  `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"contentType"`
	PartSize       int64   `protobuf:"varint,6,opt,name=part_size,json=partSize,proto3" json:"partSize"`
	TotalParts     int32   `protobuf:"varint,7,opt,name=total_parts,json=totalParts,proto3" json:"totalParts"`
	Md5            string  `protobuf:"bytes,8,opt,name=md5,proto3" json:"md5"`
	Status         string  `protobuf:"bytes,9,opt,name=status,proto3" json:"status"`
	Reused         bool    `protobuf:"varint,10,opt,name=reused,proto3" json:"reused"`
	CompletedParts []int32 `protobuf:"varint,11,rep,packed,name=completed_parts,json=completedParts,proto3" json:"completedParts"`
}

func (m *UploadSession) Reset()         { *m = UploadSession{} }
func (m *UploadSession) String() string { return proto.CompactTextString(m) }
func (*UploadSession) ProtoMessage()    {}
func (*UploadSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{0}
}
func (m *UploadSession) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UploadSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UploadSession.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UploadSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadSession.Merge(m, src)
}
func (m *UploadSession) XXX_Size() int {
	return m.Size()
}
func (m *UploadSession) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadSession.DiscardUnknown(m)
}

var xxx_messageInfo_UploadSession proto.InternalMessageInfo

func (m *UploadSession) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UploadSession) GetUploadId() string {
	if m != nil {
		return m.UploadId
	}
	return ""
}

func (m *UploadSession) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *UploadSession) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UploadSession) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *UploadSession) GetPartSize() int64 {
	if m != nil {
		return m.PartSize
	}
	return 0
}

func (m *UploadSession) GetTotalParts() int32 {
	if m != nil {
		return m.TotalParts
	}
	return 0
}

func (m *UploadSession) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *UploadSession) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UploadSession) GetReused() bool {
	if m != nil {
		return m.Reused
	}
	return false
}

func (m *UploadSession) GetCompletedParts() []int32 {
	if m != nil {
		return m.CompletedParts
	}
	return nil
}

type CreateUploadReq struct {
	FileSize       int64  `protobuf:"varint,1,opt,name=file_size,json=fileSize,proto3" json:"fileSize"`
	FileName       string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"fileName"`
	ContentType    string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"contentType"`
	ExpiresSeconds int64  `protobuf:"varint,4,opt,name=expires_seconds,json=expiresSeconds,proto3" json:"expiresSeconds"`
	Md5            string `protobuf:"bytes,5,opt,name=md5,proto3" json:"md5"`
}

func (m *CreateUploadReq) Reset()         { *m = CreateUploadReq{} }
func (m *CreateUploadReq) String() string { return proto.CompactTextString(m) }
func (*CreateUploadReq) ProtoMessage()    {}
func (*CreateUploadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{1}
}
func (m *CreateUploadReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateUploadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateUploadReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateUploadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUploadReq.Merge(m, src)
}
func (m *CreateUploadReq) XXX_Size() int {
	return m.Size()
}
func (m *CreateUploadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUploadReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUploadReq proto.InternalMessageInfo

func (m *CreateUploadReq) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func (m *CreateUploadReq) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *CreateUploadReq) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *CreateUploadReq) GetExpiresSeconds() int64 {
	if m != nil {
		return m.ExpiresSeconds
	}
	return 0
}

func (m *CreateUploadReq) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

type CreateUploadResp struct {
	CommonResp *grpcep.CommonResp `protobuf:"bytes,1,opt,name=common_resp,json=commonResp,proto3" json:"common_resp"`
	Upload     *UploadSession     `protobuf:"bytes,2,opt,name=upload,proto3" json:"upload"`
}

func (m *CreateUploadResp) Reset()         { *m = CreateUploadResp{} }
func (m *CreateUploadResp) String() string { return proto.CompactTextString(m) }
func (*CreateUploadResp) ProtoMessage()    {}
func (*CreateUploadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{2}
}
func (m *CreateUploadResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateUploadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateUploadResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateUploadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUploadResp.Merge(m, src)
}
func (m *CreateUploadResp) XXX_Size() int {
	return m.Size()
}
func (m *CreateUploadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUploadResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUploadResp proto.InternalMessageInfo

func (m *CreateUploadResp) GetCommonResp() *grpcep.CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

func (m *CreateUploadResp) GetUpload() *UploadSession {
	if m != nil {
		return m.Upload
	}
	return nil
}

type GetUploadPartURLReq struct {
	Uuid       string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
	UploadId   string `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"uploadId"`
	PartNumber int32  `protobuf:"varint,3,opt,name=part_number,json=partNumber,proto3" json:"partNumber"`
	FileSize   int64  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"fileSize"`
}

func (m *GetUploadPartURLReq) Reset()         { *m = GetUploadPartURLReq{} }
func (m *GetUploadPartURLReq) String() string { return proto.CompactTextString(m) }
func (*GetUploadPartURLReq) ProtoMessage()    {}
func (*GetUploadPartURLReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{3}
}
func (m *GetUploadPartURLReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetUploadPartURLReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetUploadPartURLReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetUploadPartURLReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUploadPartURLReq.Merge(m, src)
}
func (m *GetUploadPartURLReq) XXX_Size() int {
	return m.Size()
}
func (m *GetUploadPartURLReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUploadPartURLReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUploadPartURLReq proto.InternalMessageInfo

func (m *GetUploadPartURLReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetUploadPartURLReq) GetUploadId() string {
	if m != nil {
		return m.UploadId
	}
	return ""
}

func (m *GetUploadPartURLReq) GetPartNumber() int32 {
	if m != nil {
		return m.PartNumber
	}
	return 0
}

func (m *GetUploadPartURLReq) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

type GetUploadPartURLResp struct {
	CommonResp *grpcep.CommonResp `protobuf:"bytes,1,opt,name=common_resp,json=commonResp,proto3" json:"common_resp"`
	Url        string             `protobuf:"bytes,2,opt,name=url,proto3" json:"url"`
}

func (m *GetUploadPartURLResp) Reset()         { *m = GetUploadPartURLResp{} }
func (m *GetUploadPartURLResp) String() string { return proto.CompactTextString(m) }
func (*GetUploadPartURLResp) ProtoMessage()    {}
func (*GetUploadPartURLResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{4}
}
func (m *GetUploadPartURLResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetUploadPartURLResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetUploadPartURLResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetUploadPartURLResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUploadPartURLResp.Merge(m, src)
}
func (m *GetUploadPartURLResp) XXX_Size() int {
	return m.Size()
}
func (m *GetUploadPartURLResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUploadPartURLResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUploadPartURLResp proto.InternalMessageInfo

func (m *GetUploadPartURLResp) GetCommonResp() *grpcep.CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

func (m *GetUploadPartURLResp) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CompleteUploadReq struct {
	Uuid                  string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
	UploadId              string `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3" json:"uploadId"`
	PreviewExpiresSeconds int64  `protobuf:"varint,3,opt,name=preview_expires_seconds,json=previewExpiresSeconds,proto3" json:"previewExpiresSeconds"`
}

func (m *CompleteUploadReq) Reset()         { *m = CompleteUploadReq{} }
func (m *CompleteUploadReq) String() string { return proto.CompactTextString(m) }
func (*CompleteUploadReq) ProtoMessage()    {}
func (*CompleteUploadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{5}
}
func (m *CompleteUploadReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CompleteUploadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CompleteUploadReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CompleteUploadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteUploadReq.Merge(m, src)
}
func (m *CompleteUploadReq) XXX_Size() int {
	return m.Size()
}
func (m *CompleteUploadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteUploadReq.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteUploadReq proto.InternalMessageInfo

func (m *CompleteUploadReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *CompleteUploadReq) GetUploadId() string {
	if m != nil {
		return m.UploadId
	}
	return ""
}

func (m *CompleteUploadReq) GetPreviewExpiresSeconds() int64 {
	if m != nil {
		return m.PreviewExpiresSeconds
	}
	return 0
}

type CompleteUploadResp struct {
	CommonResp *grpcep.CommonResp `protobuf:"bytes,1,opt,name=common_resp,json=commonResp,proto3" json:"common_resp"`
	Url        string             `protobuf:"bytes,2,opt,name=url,proto3" json:"url"`
}

func (m *CompleteUploadResp) Reset()         { *m = CompleteUploadResp{} }
func (m *CompleteUploadResp) String() string { return proto.CompactTextString(m) }
func (*CompleteUploadResp) ProtoMessage()    {}
func (*CompleteUploadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{6}
}
func (m *CompleteUploadResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CompleteUploadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CompleteUploadResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CompleteUploadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteUploadResp.Merge(m, src)
}
func (m *CompleteUploadResp) XXX_Size() int {
	return m.Size()
}
func (m *CompleteUploadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteUploadResp.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteUploadResp proto.InternalMessageInfo

func (m *CompleteUploadResp) GetCommonResp() *grpcep.CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

func (m *CompleteUploadResp) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GetUploadURLReq struct {
	Uuid           string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
	ExpiresSeconds int64  `protobuf:"varint,2,opt,name=expires_seconds,json=expiresSeconds,proto3" json:"expiresSeconds"`
	FileName       string `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"fileName"`
}

func (m *GetUploadURLReq) Reset()         { *m = GetUploadURLReq{} }
func (m *GetUploadURLReq) String() string { return proto.CompactTextString(m) }
func (*GetUploadURLReq) ProtoMessage()    {}
func (*GetUploadURLReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{7}
}
func (m *GetUploadURLReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetUploadURLReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetUploadURLReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetUploadURLReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUploadURLReq.Merge(m, src)
}
func (m *GetUploadURLReq) XXX_Size() int {
	return m.Size()
}
func (m *GetUploadURLReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUploadURLReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUploadURLReq proto.InternalMessageInfo

func (m *GetUploadURLReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetUploadURLReq) GetExpiresSeconds() int64 {
	if m != nil {
		return m.ExpiresSeconds
	}
	return 0
}

func (m *GetUploadURLReq) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

type GetUploadURLResp struct {
	CommonResp *grpcep.CommonResp `protobuf:"bytes,1,opt,name=common_resp,json=commonResp,proto3" json:"common_resp"`
	Url        string             `protobuf:"bytes,2,opt,name=url,proto3" json:"url"`
}

func (m *GetUploadURLResp) Reset()         { *m = GetUploadURLResp{} }
func (m *GetUploadURLResp) String() string { return proto.CompactTextString(m) }
func (*GetUploadURLResp) ProtoMessage()    {}
func (*GetUploadURLResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_91b94b655bd2a7e5, []int{8}
}
func (m *GetUploadURLResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetUploadURLResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetUploadURLResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetUploadURLResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUploadURLResp.Merge(m, src)
}
func (m *GetUploadURLResp) XXX_Size() int {
	return m.Size()
}
func (m *GetUploadURLResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUploadURLResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUploadURLResp proto.InternalMessageInfo

func (m *GetUploadURLResp) GetCommonResp() *grpcep.CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

func (m *GetUploadURLResp) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*UploadSession)(nil), "system_proto.UploadSession")
	proto.RegisterType((*CreateUploadReq)(nil), "system_proto.CreateUploadReq")
	proto.RegisterType((*CreateUploadResp)(nil), "system_proto.CreateUploadResp")
	proto.RegisterType((*GetUploadPartURLReq)(nil), "system_proto.GetUploadPartURLReq")
	proto.RegisterType((*GetUploadPartURLResp)(nil), "system_proto.GetUploadPartURLResp")
	proto.RegisterType((*CompleteUploadReq)(nil), "system_proto.CompleteUploadReq")
	proto.RegisterType((*CompleteUploadResp)(nil), "system_proto.CompleteUploadResp")
	proto.RegisterType((*GetUploadURLReq)(nil), "system_proto.GetUploadURLReq")
	proto.RegisterType((*GetUploadURLResp)(nil), "system_proto.GetUploadURLResp")
}

func init() { proto.RegisterFile("upload.proto", fileDescriptor_91b94b655bd2a7e5) }

var fileDescriptor_91b94b655bd2a7e5 = []byte{
	// 710 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x54, 0x3d, 0x6f, 0xd4, 0x4a,
	0x14, 0xcd, 0xc4, 0xd9, 0xcd, 0xee, 0xec, 0xbe, 0x6c, 0x9e, 0xdf, 0x43, 0x38, 0x01, 0xad, 0x57,
	0xa6, 0x59, 0x8a, 0xac, 0xa5, 0x45, 0xa9, 0x52, 0x20, 0x6d, 0x40, 0x08, 0x09, 0x45, 0x30, 0x21,
	0x0d, 0x8d, 0xe5, 0xb5, 0x6f, 0x16, 0x8b, 0xb5, 0xc7, 0xf1, 0x8c, 0x09, 0xc9, 0xaf, 0xa0, 0x43,
	0xfc, 0x0a, 0x7a, 0x3a, 0x3a, 0xca, 0x94, 0x54, 0x16, 0x4a, 0x3a, 0xb7, 0xfc, 0x01, 0x34, 0x33,
	0x8e, 0xf7, 0x2b, 0x8a, 0x52, 0x44, 0x69, 0xc6, 0xf7, 0x9e, 0x7b, 0x6c, 0x9d, 0x39, 0xf7, 0x5e,
	0xe3, 0x66, 0x1a, 0x8f, 0xa9, 0xeb, 0xf7, 0xe2, 0x84, 0x72, 0xaa, 0x37, 0xd9, 0x09, 0xe3, 0x10,
	0x3a, 0x32, 0xdb, 0xdc, 0x1a, 0x05, 0xfc, 0x7d, 0x3a, 0xec, 0x79, 0x34, 0xb4, 0x47, 0x74, 0x44,
	0x6d, 0x09, 0x0f, 0xd3, 0x43, 0x99, 0xc9, 0x44, 0x46, 0xea, 0xe5, 0xcd, 0xfe, 0x14, 0x9d, 0x83,
	0x1b, 0x6e, 0xf9, 0x6e, 0xe4, 0xc3, 0x38, 0xa0, 0x91, 0x7d, 0x94, 0x06, 0xde, 0x87, 0x11, 0xb5,
	0x47, 0x49, 0xec, 0x41, 0x6c, 0x8f, 0x83, 0xa1, 0x7a, 0xc7, 0xfa, 0xa1, 0xe1, 0x7f, 0x0e, 0xa4,
	0x82, 0x7d, 0x60, 0x2c, 0xa0, 0x91, 0xfe, 0x10, 0xaf, 0xa4, 0x69, 0xe0, 0x1b, 0xa8, 0x83, 0xba,
	0xf5, 0x41, 0x2d, 0xcf, 0x4c, 0x99, 0x13, 0x79, 0xea, 0x8f, 0x71, 0x5d, 0x09, 0x76, 0x02, 0xdf,
	0x58, 0x96, 0x94, 0x66, 0x9e, 0x99, 0x35, 0x05, 0xbe, 0xf4, 0x49, 0x19, 0x89, 0x0f, 0x85, 0xd4,
	0x07, 0x43, 0x9b, 0x7c, 0x48, 0xe4, 0x44, 0x9e, 0xfa, 0x06, 0xd6, 0xd2, 0x64, 0x6c, 0xac, 0xc8,
	0xe2, 0x6a, 0x9e, 0x99, 0x22, 0x25, 0xe2, 0xd0, 0xfb, 0xb8, 0xe9, 0xd1, 0x88, 0x43, 0xc4, 0x1d,
	0x7e, 0x12, 0x83, 0x51, 0x91, 0x9c, 0x56, 0x9e, 0x99, 0x8d, 0x02, 0x7f, 0x7b, 0x12, 0x03, 0x99,
	0x4e, 0x84, 0xae, 0xd8, 0x4d, 0xb8, 0xc3, 0x82, 0x53, 0x30, 0xaa, 0x1d, 0xd4, 0xd5, 0x94, 0x2e,
	0x01, 0xee, 0x07, 0xa7, 0x40, 0xca, 0x48, 0xb7, 0x71, 0x83, 0x53, 0xee, 0x8e, 0x1d, 0x81, 0x30,
	0x63, 0xb5, 0x83, 0xba, 0x95, 0xc1, 0x5a, 0x9e, 0x99, 0x58, 0xc2, 0xaf, 0x05, 0x4a, 0xa6, 0x62,
	0x21, 0x35, 0xf4, 0xb7, 0x8d, 0xda, 0x44, 0x6a, 0xe8, 0x6f, 0x13, 0x71, 0xe8, 0x16, 0xae, 0x32,
	0xee, 0xf2, 0x94, 0x19, 0x75, 0x59, 0xc5, 0x79, 0x66, 0x16, 0x08, 0x29, 0x9e, 0x82, 0x93, 0x40,
	0xca, 0xc0, 0x37, 0x70, 0x07, 0x75, 0x6b, 0x8a, 0xa3, 0x10, 0x52, 0x3c, 0xf5, 0x1d, 0xdc, 0xf2,
	0x68, 0x18, 0x8f, 0x81, 0x83, 0x5f, 0xe8, 0x6a, 0x74, 0xb4, 0x6e, 0x65, 0xa0, 0xe7, 0x99, 0xb9,
	0x56, 0x96, 0x94, 0xb6, 0xb9, 0xdc, 0xfa, 0x83, 0x70, 0x6b, 0x37, 0x01, 0x97, 0x83, 0xea, 0x24,
	0x81, 0x23, 0xe1, 0xc7, 0x61, 0x30, 0x06, 0xe5, 0x07, 0x9a, 0xf8, 0x21, 0x40, 0xe5, 0xc7, 0x65,
	0x54, 0x52, 0x23, 0x37, 0x84, 0xe9, 0x96, 0x0a, 0x70, 0xcf, 0x0d, 0x0b, 0xaa, 0x88, 0x16, 0x3a,
	0xa3, 0xdd, 0xa0, 0x33, 0x3b, 0xb8, 0x05, 0x9f, 0xe2, 0x20, 0x01, 0xe6, 0x30, 0xf0, 0x68, 0xe4,
	0x33, 0xd9, 0x74, 0x4d, 0x5d, 0xad, 0x28, 0xed, 0xab, 0x0a, 0x99, 0xcb, 0x2f, 0xad, 0xaf, 0x2c,
	0x5a, 0x6f, 0x7d, 0x45, 0x78, 0x7d, 0xf6, 0xd6, 0x2c, 0xd6, 0x9f, 0xe1, 0x86, 0x47, 0xc3, 0x90,
	0x46, 0x4e, 0x02, 0x2c, 0x96, 0x17, 0x6f, 0xf4, 0xf5, 0x9e, 0x1a, 0xfb, 0xde, 0xae, 0x2c, 0x09,
	0xe2, 0xa5, 0xe6, 0x92, 0x4a, 0xb0, 0x57, 0x16, 0xf5, 0xa7, 0xb8, 0xaa, 0xa6, 0x58, 0xda, 0xd1,
	0xe8, 0x3f, 0xe8, 0x4d, 0xaf, 0x65, 0x6f, 0x66, 0x5f, 0x54, 0x3b, 0x15, 0x9d, 0x14, 0x4f, 0xeb,
	0x3b, 0xc2, 0xff, 0xbd, 0x00, 0xae, 0x88, 0xa2, 0x49, 0x07, 0xe4, 0x95, 0xe8, 0xca, 0xad, 0xed,
	0x96, 0x8d, 0x1b, 0x72, 0xdc, 0xa3, 0x34, 0x1c, 0x42, 0x22, 0xfb, 0x50, 0xcc, 0xb0, 0x80, 0xf7,
	0x24, 0x4a, 0xa6, 0xe2, 0xd9, 0x79, 0x58, 0xb9, 0x6e, 0x1e, 0xac, 0x63, 0xfc, 0xff, 0xa2, 0xf6,
	0x5b, 0xf3, 0xb6, 0xd8, 0xfb, 0xe5, 0xc5, 0xbd, 0xb7, 0xbe, 0x21, 0xfc, 0xef, 0x6e, 0x31, 0xda,
	0x93, 0x49, 0xbe, 0x35, 0xcf, 0xde, 0xe0, 0xfb, 0x71, 0x02, 0x1f, 0x03, 0x38, 0x76, 0xe6, 0x07,
	0x52, 0x93, 0x86, 0x6c, 0xe4, 0x99, 0x79, 0xaf, 0xa0, 0x3c, 0x9f, 0x9d, 0xcb, 0xab, 0x61, 0x2b,
	0xc5, 0xfa, 0xbc, 0xe0, 0xbb, 0x30, 0xea, 0x0b, 0xc2, 0xad, 0xb2, 0x45, 0x37, 0x1a, 0xad, 0x2b,
	0x96, 0x70, 0xf9, 0xc6, 0x4b, 0x38, 0xf3, 0x83, 0xd0, 0xae, 0xfb, 0x41, 0x58, 0x0c, 0xaf, 0xcf,
	0x0a, 0xbb, 0x03, 0x3b, 0x06, 0x8f, 0x7e, 0x9e, 0xb7, 0xd1, 0xd9, 0x79, 0x1b, 0xfd, 0x3e, 0x6f,
	0xa3, 0xcf, 0x17, 0xed, 0xa5, 0xb3, 0x8b, 0xf6, 0xd2, 0xaf, 0x8b, 0xf6, 0xd2, 0xbb, 0x7a, 0xcf,
	0xde, 0x51, 0xab, 0x3b, 0xac, 0xca, 0xdd, 0x7d, 0xf2, 0x37, 0x00, 0x00, 0xff, 0xff, 0x54, 0xa2,
	0xd3, 0x7c, 0x70, 0x07, 0x00, 0x00,
}

func (m *UploadSession) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UploadSession) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UploadSession) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CompletedParts) > 0 {
		dAtA2 := make([]byte, len(m.CompletedParts)*10)
		var j1 int
		for _, num1 := range m.CompletedParts {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintUpload(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x5a
	}
	if m.Reused {
		i--
		if m.Reused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Md5) > 0 {
		i -= len(m.Md5)
		copy(dAtA[i:], m.Md5)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.Md5)))
		i--
		dAtA[i] = 0x42
	}
	if m.TotalParts != 0 {
		i = encodeVarintUpload(dAtA, i, uint64(m.TotalParts))
		i--
		dAtA[i] = 0x38
	}
	if m.PartSize != 0 {
		i = encodeVarintUpload(dAtA, i, uint64(m.PartSize))
		i--
		dAtA[i] = 0x30
	}
	if len(m.ContentType) > 0 {
		i -= len(m.ContentType)
		copy(dAtA[i:], m.ContentType)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.ContentType)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Mode) > 0 {
		i -= len(m.Mode)
		copy(dAtA[i:], m.Mode)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.Mode)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.UploadId) > 0 {
		i -= len(m.UploadId)
		copy(dAtA[i:], m.UploadId)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.UploadId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreateUploadReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateUploadReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateUploadReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Md5) > 0 {
		i -= len(m.Md5)
		copy(dAtA[i:], m.Md5)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.Md5)))
		i--
		dAtA[i] = 0x2a
	}
	if m.ExpiresSeconds != 0 {
		i = encodeVarintUpload(dAtA, i, uint64(m.ExpiresSeconds))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ContentType) > 0 {
		i -= len(m.ContentType)
		copy(dAtA[i:], m.ContentType)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.ContentType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FileName) > 0 {
		i -= len(m.FileName)
		copy(dAtA[i:], m.FileName)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.FileName)))
		i--
		dAtA[i] = 0x12
	}
	if m.FileSize != 0 {
		i = encodeVarintUpload(dAtA, i, uint64(m.FileSize))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *CreateUploadResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateUploadResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreateUploadResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Upload != nil {
		{
			size, err := m.Upload.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintUpload(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.CommonResp != nil {
		{
			size, err := m.CommonResp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintUpload(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetUploadPartURLReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetUploadPartURLReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetUploadPartURLReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FileSize != 0 {
		i = encodeVarintUpload(dAtA, i, uint64(m.FileSize))
		i--
		dAtA[i] = 0x20
	}
	if m.PartNumber != 0 {
		i = encodeVarintUpload(dAtA, i, uint64(m.PartNumber))
		i--
		dAtA[i] = 0x18
	}
	if len(m.UploadId) > 0 {
		i -= len(m.UploadId)
		copy(dAtA[i:], m.UploadId)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.UploadId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetUploadPartURLResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetUploadPartURLResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetUploadPartURLResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x12
	}
	if m.CommonResp != nil {
		{
			size, err := m.CommonResp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintUpload(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CompleteUploadReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CompleteUploadReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CompleteUploadReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PreviewExpiresSeconds != 0 {
		i = encodeVarintUpload(dAtA, i, uint64(m.PreviewExpiresSeconds))
		i--
		dAtA[i] = 0x18
	}
	if len(m.UploadId) > 0 {
		i -= len(m.UploadId)
		copy(dAtA[i:], m.UploadId)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.UploadId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CompleteUploadResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CompleteUploadResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CompleteUploadResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x12
	}
	if m.CommonResp != nil {
		{
			size, err := m.CommonResp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintUpload(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetUploadURLReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetUploadURLReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetUploadURLReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FileName) > 0 {
		i -= len(m.FileName)
		copy(dAtA[i:], m.FileName)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.FileName)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ExpiresSeconds != 0 {
		i = encodeVarintUpload(dAtA, i, uint64(m.ExpiresSeconds))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Uuid) > 0 {
		i -= len(m.Uuid)
		copy(dAtA[i:], m.Uuid)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.Uuid)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GetUploadURLResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetUploadURLResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GetUploadURLResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintUpload(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x12
	}
	if m.CommonResp != nil {
		{
			size, err := m.CommonResp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintUpload(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintUpload(dAtA []byte, offset int, v uint64) int {
	offset -= sovUpload(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UploadSession) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	l = len(m.UploadId)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	l = len(m.Mode)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	l = len(m.ContentType)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	if m.PartSize != 0 {
		n += 1 + sovUpload(uint64(m.PartSize))
	}
	if m.TotalParts != 0 {
		n += 1 + sovUpload(uint64(m.TotalParts))
	}
	l = len(m.Md5)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	if m.Reused {
		n += 2
	}
	if len(m.CompletedParts) > 0 {
		l = 0
		for _, e := range m.CompletedParts {
			l += sovUpload(uint64(e))
		}
		n += 1 + sovUpload(uint64(l)) + l
	}
	return n
}

func (m *CreateUploadReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FileSize != 0 {
		n += 1 + sovUpload(uint64(m.FileSize))
	}
	l = len(m.FileName)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	l = len(m.ContentType)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	if m.ExpiresSeconds != 0 {
		n += 1 + sovUpload(uint64(m.ExpiresSeconds))
	}
	l = len(m.Md5)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	return n
}

func (m *CreateUploadResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CommonResp != nil {
		l = m.CommonResp.Size()
		n += 1 + l + sovUpload(uint64(l))
	}
	if m.Upload != nil {
		l = m.Upload.Size()
		n += 1 + l + sovUpload(uint64(l))
	}
	return n
}

func (m *GetUploadPartURLReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	l = len(m.UploadId)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	if m.PartNumber != 0 {
		n += 1 + sovUpload(uint64(m.PartNumber))
	}
	if m.FileSize != 0 {
		n += 1 + sovUpload(uint64(m.FileSize))
	}
	return n
}

func (m *GetUploadPartURLResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CommonResp != nil {
		l = m.CommonResp.Size()
		n += 1 + l + sovUpload(uint64(l))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	return n
}

func (m *CompleteUploadReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	l = len(m.UploadId)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	if m.PreviewExpiresSeconds != 0 {
		n += 1 + sovUpload(uint64(m.PreviewExpiresSeconds))
	}
	return n
}

func (m *CompleteUploadResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CommonResp != nil {
		l = m.CommonResp.Size()
		n += 1 + l + sovUpload(uint64(l))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	return n
}

func (m *GetUploadURLReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	if m.ExpiresSeconds != 0 {
		n += 1 + sovUpload(uint64(m.ExpiresSeconds))
	}
	l = len(m.FileName)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	return n
}

func (m *GetUploadURLResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CommonResp != nil {
		l = m.CommonResp.Size()
		n += 1 + l + sovUpload(uint64(l))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovUpload(uint64(l))
	}
	return n
}

func sovUpload(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUpload(x uint64) (n int) {
	return sovUpload(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UploadSession) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUpload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UploadSession: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UploadSession: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UploadId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartSize", wireType)
			}
			m.PartSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PartSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalParts", wireType)
			}
			m.TotalParts = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalParts |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Md5", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Md5 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Reused = bool(v != 0)
		case 11:
			if wireType == 0 {
				var v int32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowUpload
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.CompletedParts = append(m.CompletedParts, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowUpload
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthUpload
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthUpload
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.CompletedParts) == 0 {
					m.CompletedParts = make([]int32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowUpload
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.CompletedParts = append(m.CompletedParts, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletedParts", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipUpload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUpload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateUploadReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUpload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateUploadReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateUploadReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSize", wireType)
			}
			m.FileSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FileSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresSeconds", wireType)
			}
			m.ExpiresSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Md5", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Md5 = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUpload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUpload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateUploadResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUpload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateUploadResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateUploadResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonResp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CommonResp == nil {
				m.CommonResp = &grpcep.CommonResp{}
			}
			if err := m.CommonResp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Upload", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Upload == nil {
				m.Upload = &UploadSession{}
			}
			if err := m.Upload.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUpload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUpload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetUploadPartURLReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUpload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetUploadPartURLReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetUploadPartURLReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UploadId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartNumber", wireType)
			}
			m.PartNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PartNumber |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileSize", wireType)
			}
			m.FileSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FileSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipUpload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUpload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetUploadPartURLResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUpload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetUploadPartURLResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetUploadPartURLResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonResp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CommonResp == nil {
				m.CommonResp = &grpcep.CommonResp{}
			}
			if err := m.CommonResp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUpload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUpload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CompleteUploadReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUpload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CompleteUploadReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CompleteUploadReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UploadId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UploadId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviewExpiresSeconds", wireType)
			}
			m.PreviewExpiresSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PreviewExpiresSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipUpload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUpload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CompleteUploadResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUpload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CompleteUploadResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CompleteUploadResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonResp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CommonResp == nil {
				m.CommonResp = &grpcep.CommonResp{}
			}
			if err := m.CommonResp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUpload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUpload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetUploadURLReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUpload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetUploadURLReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetUploadURLReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresSeconds", wireType)
			}
			m.ExpiresSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresSeconds |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUpload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUpload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetUploadURLResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUpload
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetUploadURLResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetUploadURLResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonResp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CommonResp == nil {
				m.CommonResp = &grpcep.CommonResp{}
			}
			if err := m.CommonResp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUpload
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUpload
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUpload(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUpload
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUpload(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUpload
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUpload
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUpload
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUpload
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUpload
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUpload        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUpload          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUpload = fmt.Errorf("proto: unexpected end of group")
)
