// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mcp.proto

package aiagent

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpcep "github.com/gly-hub/quickgo/grpcep"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MCPKV struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
}

func (m *MCPKV) Reset()         { *m = MCPKV{} }
func (m *MCPKV) String() string { return proto.CompactTextString(m) }
func (*MCPKV) ProtoMessage()    {}
func (*MCPKV) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfb46e59039c8a2f, []int{0}
}
func (m *MCPKV) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MCPKV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MCPKV.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MCPKV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MCPKV.Merge(m, src)
}
func (m *MCPKV) XXX_Size() int {
	return m.Size()
}
func (m *MCPKV) XXX_DiscardUnknown() {
	xxx_messageInfo_MCPKV.DiscardUnknown(m)
}

var xxx_messageInfo_MCPKV proto.InternalMessageInfo

func (m *MCPKV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MCPKV) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AgentMCPServer struct {
	Id          string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name        string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Description string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	Type        string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type"`
	Enabled     bool     `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled"`
	Command     string   `protobuf:"bytes,6,opt,name=command,proto3" json:"command,omitempty"`
	Args        []string `protobuf:"bytes,7,rep,name=args,proto3" json:"args,omitempty"`
	Env         []*MCPKV `protobuf:"bytes,8,rep,name=env,proto3" json:"env,omitempty"`
	Url         string   `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`
	Headers     []*MCPKV `protobuf:"bytes,10,rep,name=headers,proto3" json:"headers,omitempty"`
	UpdatedAt   int64    `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updatedAt"`
	ConfigJson  string   `protobuf:"bytes,12,opt,name=config_json,json=configJson,proto3" json:"configJson,omitempty"`
}

func (m *AgentMCPServer) Reset()         { *m = AgentMCPServer{} }
func (m *AgentMCPServer) String() string { return proto.CompactTextString(m) }
func (*AgentMCPServer) ProtoMessage()    {}
func (*AgentMCPServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfb46e59039c8a2f, []int{1}
}
func (m *AgentMCPServer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AgentMCPServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AgentMCPServer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AgentMCPServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentMCPServer.Merge(m, src)
}
func (m *AgentMCPServer) XXX_Size() int {
	return m.Size()
}
func (m *AgentMCPServer) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentMCPServer.DiscardUnknown(m)
}

var xxx_messageInfo_AgentMCPServer proto.InternalMessageInfo

func (m *AgentMCPServer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AgentMCPServer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AgentMCPServer) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AgentMCPServer) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AgentMCPServer) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *AgentMCPServer) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *AgentMCPServer) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *AgentMCPServer) GetEnv() []*MCPKV {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *AgentMCPServer) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AgentMCPServer) GetHeaders() []*MCPKV {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *AgentMCPServer) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *AgentMCPServer) GetConfigJson() string {
	if m != nil {
		return m.ConfigJson
	}
	return ""
}

type ListMCPServersReq struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"userId"`
}

func (m *ListMCPServersReq) Reset()         { *m = ListMCPServersReq{} }
func (m *ListMCPServersReq) String() string { return proto.CompactTextString(m) }
func (*ListMCPServersReq) ProtoMessage()    {}
func (*ListMCPServersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfb46e59039c8a2f, []int{2}
}
func (m *ListMCPServersReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListMCPServersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListMCPServersReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListMCPServersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMCPServersReq.Merge(m, src)
}
func (m *ListMCPServersReq) XXX_Size() int {
	return m.Size()
}
func (m *ListMCPServersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMCPServersReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListMCPServersReq proto.InternalMessageInfo

func (m *ListMCPServersReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListMCPServersResp struct {
	CommonResp *grpcep.CommonResp `protobuf:"bytes,1,opt,name=common_resp,json=commonResp,proto3" json:"common_resp"`
	Servers    []*AgentMCPServer  `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers"`
}

func (m *ListMCPServersResp) Reset()         { *m = ListMCPServersResp{} }
func (m *ListMCPServersResp) String() string { return proto.CompactTextString(m) }
func (*ListMCPServersResp) ProtoMessage()    {}
func (*ListMCPServersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfb46e59039c8a2f, []int{3}
}
func (m *ListMCPServersResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListMCPServersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListMCPServersResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListMCPServersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMCPServersResp.Merge(m, src)
}
func (m *ListMCPServersResp) XXX_Size() int {
	return m.Size()
}
func (m *ListMCPServersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMCPServersResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListMCPServersResp proto.InternalMessageInfo

func (m *ListMCPServersResp) GetCommonResp() *grpcep.CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

func (m *ListMCPServersResp) GetServers() []*AgentMCPServer {
	if m != nil {
		return m.Servers
	}
	return nil
}

type SaveMCPServerReq struct {
	UserId string          `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"userId"`
	Server *AgentMCPServer `protobuf:"bytes,2,opt,name=server,proto3" json:"server"`
}

func (m *SaveMCPServerReq) Reset()         { *m = SaveMCPServerReq{} }
func (m *SaveMCPServerReq) String() string { return proto.CompactTextString(m) }
func (*SaveMCPServerReq) ProtoMessage()    {}
func (*SaveMCPServerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfb46e59039c8a2f, []int{4}
}
func (m *SaveMCPServerReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SaveMCPServerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SaveMCPServerReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SaveMCPServerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMCPServerReq.Merge(m, src)
}
func (m *SaveMCPServerReq) XXX_Size() int {
	return m.Size()
}
func (m *SaveMCPServerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMCPServerReq.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMCPServerReq proto.InternalMessageInfo

func (m *SaveMCPServerReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SaveMCPServerReq) GetServer() *AgentMCPServer {
	if m != nil {
		return m.Server
	}
	return nil
}

type SaveMCPServerResp struct {
	CommonResp *grpcep.CommonResp `protobuf:"bytes,1,opt,name=common_resp,json=commonResp,proto3" json:"common_resp"`
	Server     *AgentMCPServer    `protobuf:"bytes,2,opt,name=server,proto3" json:"server"`
}

func (m *SaveMCPServerResp) Reset()         { *m = SaveMCPServerResp{} }
func (m *SaveMCPServerResp) String() string { return proto.CompactTextString(m) }
func (*SaveMCPServerResp) ProtoMessage()    {}
func (*SaveMCPServerResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfb46e59039c8a2f, []int{5}
}
func (m *SaveMCPServerResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SaveMCPServerResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SaveMCPServerResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SaveMCPServerResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveMCPServerResp.Merge(m, src)
}
func (m *SaveMCPServerResp) XXX_Size() int {
	return m.Size()
}
func (m *SaveMCPServerResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveMCPServerResp.DiscardUnknown(m)
}

var xxx_messageInfo_SaveMCPServerResp proto.InternalMessageInfo

func (m *SaveMCPServerResp) GetCommonResp() *grpcep.CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

func (m *SaveMCPServerResp) GetServer() *AgentMCPServer {
	if m != nil {
		return m.Server
	}
	return nil
}

type DeleteMCPServerReq struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"userId"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id"`
}

func (m *DeleteMCPServerReq) Reset()         { *m = DeleteMCPServerReq{} }
func (m *DeleteMCPServerReq) String() string { return proto.CompactTextString(m) }
func (*DeleteMCPServerReq) ProtoMessage()    {}
func (*DeleteMCPServerReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfb46e59039c8a2f, []int{6}
}
func (m *DeleteMCPServerReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteMCPServerReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteMCPServerReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteMCPServerReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMCPServerReq.Merge(m, src)
}
func (m *DeleteMCPServerReq) XXX_Size() int {
	return m.Size()
}
func (m *DeleteMCPServerReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMCPServerReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMCPServerReq proto.InternalMessageInfo

func (m *DeleteMCPServerReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteMCPServerReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteMCPServerResp struct {
	CommonResp *grpcep.CommonResp `protobuf:"bytes,1,opt,name=common_resp,json=commonResp,proto3" json:"common_resp"`
	Id         string             `protobuf:"bytes,2,opt,name=id,proto3" json:"id"`
}

func (m *DeleteMCPServerResp) Reset()         { *m = DeleteMCPServerResp{} }
func (m *DeleteMCPServerResp) String() string { return proto.CompactTextString(m) }
func (*DeleteMCPServerResp) ProtoMessage()    {}
func (*DeleteMCPServerResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfb46e59039c8a2f, []int{7}
}
func (m *DeleteMCPServerResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteMCPServerResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteMCPServerResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteMCPServerResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMCPServerResp.Merge(m, src)
}
func (m *DeleteMCPServerResp) XXX_Size() int {
	return m.Size()
}
func (m *DeleteMCPServerResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMCPServerResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMCPServerResp proto.InternalMessageInfo

func (m *DeleteMCPServerResp) GetCommonResp() *grpcep.CommonResp {
	if m != nil {
		return m.CommonResp
	}
	return nil
}

func (m *DeleteMCPServerResp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*MCPKV)(nil), "mcp_proto.MCPKV")
	proto.RegisterType((*AgentMCPServer)(nil), "mcp_proto.AgentMCPServer")
	proto.RegisterType((*ListMCPServersReq)(nil), "mcp_proto.ListMCPServersReq")
	proto.RegisterType((*ListMCPServersResp)(nil), "mcp_proto.ListMCPServersResp")
	proto.RegisterType((*SaveMCPServerReq)(nil), "mcp_proto.SaveMCPServerReq")
	proto.RegisterType((*SaveMCPServerResp)(nil), "mcp_proto.SaveMCPServerResp")
	proto.RegisterType((*DeleteMCPServerReq)(nil), "mcp_proto.DeleteMCPServerReq")
	proto.RegisterType((*DeleteMCPServerResp)(nil), "mcp_proto.DeleteMCPServerResp")
}

func init() { proto.RegisterFile("mcp.proto", fileDescriptor_dfb46e59039c8a2f) }

var fileDescriptor_dfb46e59039c8a2f = []byte{
	// 668 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0xae, 0xe3, 0x34, 0x6e, 0x4e, 0x6e, 0x7b, 0x9b, 0xb9, 0x17, 0x34, 0xad, 0x50, 0x1c, 0xb9,
	0x80, 0xb2, 0x68, 0x6d, 0x51, 0x84, 0x04, 0x42, 0x48, 0x34, 0xe9, 0x86, 0x9f, 0x4a, 0xc5, 0x95,
	0x58, 0xb0, 0x89, 0x26, 0xf6, 0xd4, 0x1d, 0x6a, 0xcf, 0xb8, 0xfe, 0x89, 0xd4, 0xb7, 0x60, 0xc9,
	0x02, 0x89, 0xd7, 0x61, 0xd9, 0x25, 0x2b, 0x0b, 0xb5, 0x3b, 0x3f, 0x05, 0xf2, 0xd8, 0x69, 0x4c,
	0x51, 0x11, 0x82, 0x6e, 0x66, 0xce, 0xf9, 0xe6, 0x3b, 0xdf, 0xf9, 0xc9, 0x89, 0xa1, 0x1d, 0x38,
	0xa1, 0x19, 0x46, 0x22, 0x11, 0xa8, 0x30, 0xc7, 0xd2, 0x5c, 0xdf, 0xf2, 0x58, 0x72, 0x94, 0x4e,
	0x4c, 0x47, 0x04, 0x96, 0x27, 0x3c, 0x61, 0x49, 0x78, 0x92, 0x1e, 0x4a, 0x4f, 0x3a, 0xd2, 0x2a,
	0x23, 0xd7, 0xb7, 0x6b, 0xf4, 0x84, 0x92, 0x60, 0xcb, 0x25, 0xdc, 0xa5, 0x3e, 0x13, 0xdc, 0x3a,
	0x49, 0x99, 0x73, 0xec, 0x09, 0xcb, 0x8b, 0x42, 0x87, 0x86, 0x96, 0xcf, 0x26, 0x65, 0x8c, 0x31,
	0x82, 0xc5, 0xbd, 0xd1, 0xfe, 0xab, 0xb7, 0x68, 0x0d, 0xd4, 0x63, 0x7a, 0x8a, 0x95, 0xbe, 0x32,
	0x68, 0x0f, 0xb5, 0x3c, 0xd3, 0x0b, 0xd7, 0x2e, 0x0e, 0xa4, 0xc3, 0xe2, 0x94, 0xf8, 0x29, 0xc5,
	0x0d, 0xf9, 0xd8, 0xce, 0x33, 0xbd, 0x04, 0xec, 0xf2, 0x32, 0x3e, 0x37, 0x61, 0x65, 0xc7, 0xa3,
	0x3c, 0xd9, 0x1b, 0xed, 0x1f, 0xd0, 0x68, 0x4a, 0x23, 0x74, 0x1b, 0x1a, 0xcc, 0xad, 0xd4, 0x5a,
	0x79, 0xa6, 0x37, 0x98, 0x6b, 0x37, 0x98, 0x8b, 0xee, 0x40, 0x93, 0x93, 0x60, 0x26, 0xb5, 0x94,
	0x67, 0xba, 0xf4, 0x6d, 0x79, 0xa2, 0x07, 0xd0, 0x71, 0x69, 0xec, 0x44, 0x2c, 0x4c, 0x98, 0xe0,
	0x58, 0x95, 0xa4, 0x7f, 0xf3, 0x4c, 0xaf, 0xc3, 0x76, 0xdd, 0x29, 0x04, 0x93, 0xd3, 0x90, 0xe2,
	0xe6, 0x5c, 0xb0, 0xf0, 0x6d, 0x79, 0xa2, 0x7b, 0xa0, 0x51, 0x4e, 0x26, 0x3e, 0x75, 0xf1, 0x62,
	0x5f, 0x19, 0x2c, 0x0d, 0x3b, 0x79, 0xa6, 0xcf, 0x20, 0x7b, 0x66, 0x20, 0x0b, 0x34, 0x47, 0x04,
	0x01, 0xe1, 0x2e, 0x6e, 0x49, 0x9d, 0x5b, 0x79, 0xa6, 0x77, 0x2b, 0x68, 0x53, 0x04, 0x2c, 0xa1,
	0x41, 0x98, 0x9c, 0xda, 0x33, 0x16, 0xba, 0x0f, 0x4d, 0x12, 0x79, 0x31, 0xd6, 0xfa, 0xea, 0xa0,
	0x3d, 0x44, 0x79, 0xa6, 0xaf, 0x14, 0x7e, 0x8d, 0x2a, 0xdf, 0xd1, 0x23, 0x50, 0x29, 0x9f, 0xe2,
	0xa5, 0xbe, 0x3a, 0xe8, 0x6c, 0xaf, 0x9a, 0x97, 0x3f, 0xad, 0x29, 0x87, 0x3e, 0xec, 0xe6, 0x99,
	0xbe, 0x4c, 0xf9, 0xb4, 0x16, 0x57, 0xf0, 0xd1, 0x06, 0xa8, 0x69, 0xe4, 0xe3, 0xb6, 0xac, 0x45,
	0x92, 0xd2, 0xc8, 0xaf, 0x93, 0xd2, 0xc8, 0x47, 0x3b, 0xa0, 0x1d, 0x51, 0xe2, 0xd2, 0x28, 0xc6,
	0x70, 0x8d, 0xbe, 0x6c, 0xa3, 0x22, 0xd5, 0xdb, 0xa8, 0x20, 0xb4, 0x09, 0x90, 0x86, 0x2e, 0x49,
	0xa8, 0x3b, 0x26, 0x09, 0xee, 0xf4, 0x95, 0x81, 0x3a, 0x5c, 0xce, 0x33, 0xbd, 0x5d, 0xa1, 0x3b,
	0x89, 0x3d, 0x37, 0xd1, 0x13, 0xe8, 0x38, 0x82, 0x1f, 0x32, 0x6f, 0xfc, 0x3e, 0x16, 0x1c, 0xff,
	0x23, 0xab, 0xc3, 0x79, 0xa6, 0xff, 0x5f, 0xc2, 0x2f, 0x63, 0xc1, 0x6b, 0x59, 0x60, 0x8e, 0x1a,
	0x8f, 0xa1, 0xfb, 0x9a, 0xc5, 0xf3, 0xfd, 0x88, 0x6d, 0x7a, 0x82, 0x36, 0x40, 0x4b, 0x63, 0x1a,
	0x8d, 0x2f, 0x17, 0x05, 0xf2, 0x4c, 0x6f, 0x15, 0xd0, 0x0b, 0xd7, 0xae, 0x6e, 0xe3, 0x93, 0x02,
	0xe8, 0x6a, 0x68, 0x1c, 0xa2, 0xdd, 0xa2, 0x96, 0x20, 0x10, 0x7c, 0x1c, 0xd1, 0x38, 0x94, 0xf1,
	0x9d, 0x6d, 0x64, 0x96, 0xfb, 0x6d, 0x8e, 0xe4, 0x53, 0x41, 0x2c, 0xb7, 0xa7, 0x46, 0x2d, 0xca,
	0x9a, 0x3d, 0xa2, 0xe7, 0xa0, 0xc5, 0xa5, 0x28, 0x6e, 0xc8, 0x11, 0xae, 0xd5, 0x46, 0xf8, 0xe3,
	0x46, 0x97, 0x9b, 0x53, 0xb1, 0xed, 0x99, 0x61, 0x4c, 0x61, 0xf5, 0x80, 0x4c, 0xe9, 0x25, 0xed,
	0x77, 0xfb, 0x42, 0xcf, 0xa0, 0x55, 0x6a, 0xc8, 0xbf, 0xc2, 0x2f, 0x33, 0xcb, 0xf0, 0x92, 0x6c,
	0x57, 0xb7, 0xf1, 0x51, 0x81, 0xee, 0x95, 0xc4, 0x37, 0x36, 0x95, 0xbf, 0x2c, 0xed, 0x0d, 0xa0,
	0x5d, 0xea, 0xd3, 0xe4, 0x0f, 0x86, 0x52, 0x7e, 0x35, 0x1a, 0x57, 0xbf, 0x1a, 0x46, 0x0c, 0xff,
	0xfd, 0x24, 0x79, 0x63, 0xed, 0x5e, 0x93, 0x74, 0x78, 0xf7, 0xcb, 0x79, 0x4f, 0x39, 0x3b, 0xef,
	0x29, 0xdf, 0xce, 0x7b, 0xca, 0x87, 0x8b, 0xde, 0xc2, 0xd9, 0x45, 0x6f, 0xe1, 0xeb, 0x45, 0x6f,
	0xe1, 0x1d, 0x98, 0xd6, 0x53, 0xc2, 0x48, 0x31, 0x8a, 0x49, 0x4b, 0xce, 0xe5, 0xe1, 0xf7, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xd0, 0xe3, 0x65, 0x78, 0xc2, 0x05, 0x00, 0x00,
}

func (m *MCPKV) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MCPKV) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MCPKV) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Value) > 0 {
		i -= len(m.Value)
		copy(dAtA[i:], m.Value)
		i = encodeVarintMcp(dAtA, i, uint64(len(m.Value)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintMcp(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AgentMCPServer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AgentMCPServer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AgentMCPServer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConfigJson) > 0 {
		i -= len(m.ConfigJson)
		copy(dAtA[i:], m.ConfigJson)
		i = encodeVarintMcp(dAtA, i, uint64(len(m.ConfigJson)))
		i--
		dAtA[i] = 0x62
	}
	if m.UpdatedAt != 0 {
		i = encodeVarintMcp(dAtA, i, uint64(m.UpdatedAt))
		i--
		dAtA[i] = 0x58
	}
	if len(m.Headers) > 0 {
		for iNdEx := len(m.Headers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Headers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMcp(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintMcp(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Env) > 0 {
		for iNdEx := len(m.Env) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Env[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMcp(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.Args) > 0 {
		for iNdEx := len(m.Args) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Args[iNdEx])
			copy(dAtA[i:], m.Args[iNdEx])
			i = encodeVarintMcp(dAtA, i, uint64(len(m.Args[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Command) > 0 {
		i -= len(m.Command)
		copy(dAtA[i:], m.Command)
		i = encodeVarintMcp(dAtA, i, uint64(len(m.Command)))
		i--
		dAtA[i] = 0x32
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintMcp(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintMcp(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintMcp(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintMcp(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListMCPServersReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListMCPServersReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListMCPServersReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UserId) > 0 {
		i -= len(m.UserId)
		copy(dAtA[i:], m.UserId)
		i = encodeVarintMcp(dAtA, i, uint64(len(m.UserId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListMCPServersResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListMCPServersResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListMCPServersResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Servers) > 0 {
		for iNdEx := len(m.Servers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Servers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintMcp(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.CommonResp != nil {
		{
			size, err := m.CommonResp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMcp(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SaveMCPServerReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SaveMCPServerReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SaveMCPServerReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Server != nil {
		{
			size, err := m.Server.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMcp(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.UserId) > 0 {
		i -= len(m.UserId)
		copy(dAtA[i:], m.UserId)
		i = encodeVarintMcp(dAtA, i, uint64(len(m.UserId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SaveMCPServerResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SaveMCPServerResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SaveMCPServerResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Server != nil {
		{
			size, err := m.Server.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMcp(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.CommonResp != nil {
		{
			size, err := m.CommonResp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMcp(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeleteMCPServerReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteMCPServerReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeleteMCPServerReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintMcp(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.UserId) > 0 {
		i -= len(m.UserId)
		copy(dAtA[i:], m.UserId)
		i = encodeVarintMcp(dAtA, i, uint64(len(m.UserId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeleteMCPServerResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteMCPServerResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeleteMCPServerResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintMcp(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if m.CommonResp != nil {
		{
			size, err := m.CommonResp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMcp(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMcp(dAtA []byte, offset int, v uint64) int {
	offset -= sovMcp(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MCPKV) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovMcp(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovMcp(uint64(l))
	}
	return n
}

func (m *AgentMCPServer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovMcp(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovMcp(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovMcp(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovMcp(uint64(l))
	}
	if m.Enabled {
		n += 2
	}
	l = len(m.Command)
	if l > 0 {
		n += 1 + l + sovMcp(uint64(l))
	}
	if len(m.Args) > 0 {
		for _, s := range m.Args {
			l = len(s)
			n += 1 + l + sovMcp(uint64(l))
		}
	}
	if len(m.Env) > 0 {
		for _, e := range m.Env {
			l = e.Size()
			n += 1 + l + sovMcp(uint64(l))
		}
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovMcp(uint64(l))
	}
	if len(m.Headers) > 0 {
		for _, e := range m.Headers {
			l = e.Size()
			n += 1 + l + sovMcp(uint64(l))
		}
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovMcp(uint64(m.UpdatedAt))
	}
	l = len(m.ConfigJson)
	if l > 0 {
		n += 1 + l + sovMcp(uint64(l))
	}
	return n
}

func (m *ListMCPServersReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserId)
	if l > 0 {
		n += 1 + l + sovMcp(uint64(l))
	}
	return n
}

func (m *ListMCPServersResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CommonResp != nil {
		l = m.CommonResp.Size()
		n += 1 + l + sovMcp(uint64(l))
	}
	if len(m.Servers) > 0 {
		for _, e := range m.Servers {
			l = e.Size()
			n += 1 + l + sovMcp(uint64(l))
		}
	}
	return n
}

func (m *SaveMCPServerReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserId)
	if l > 0 {
		n += 1 + l + sovMcp(uint64(l))
	}
	if m.Server != nil {
		l = m.Server.Size()
		n += 1 + l + sovMcp(uint64(l))
	}
	return n
}

func (m *SaveMCPServerResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CommonResp != nil {
		l = m.CommonResp.Size()
		n += 1 + l + sovMcp(uint64(l))
	}
	if m.Server != nil {
		l = m.Server.Size()
		n += 1 + l + sovMcp(uint64(l))
	}
	return n
}

func (m *DeleteMCPServerReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserId)
	if l > 0 {
		n += 1 + l + sovMcp(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovMcp(uint64(l))
	}
	return n
}

func (m *DeleteMCPServerResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CommonResp != nil {
		l = m.CommonResp.Size()
		n += 1 + l + sovMcp(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovMcp(uint64(l))
	}
	return n
}

func sovMcp(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMcp(x uint64) (n int) {
	return sovMcp(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MCPKV) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMcp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MCPKV: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MCPKV: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMcp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMcp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AgentMCPServer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMcp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AgentMCPServer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AgentMCPServer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Command", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Command = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Args", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Args = append(m.Args, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Env", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Env = append(m.Env, &MCPKV{})
			if err := m.Env[len(m.Env)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Headers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Headers = append(m.Headers, &MCPKV{})
			if err := m.Headers[len(m.Headers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConfigJson", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConfigJson = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMcp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMcp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListMCPServersReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMcp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListMCPServersReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListMCPServersReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMcp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMcp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListMCPServersResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMcp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListMCPServersResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListMCPServersResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonResp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CommonResp == nil {
				m.CommonResp = &grpcep.CommonResp{}
			}
			if err := m.CommonResp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Servers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Servers = append(m.Servers, &AgentMCPServer{})
			if err := m.Servers[len(m.Servers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMcp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMcp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SaveMCPServerReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMcp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SaveMCPServerReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SaveMCPServerReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Server", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Server == nil {
				m.Server = &AgentMCPServer{}
			}
			if err := m.Server.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMcp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMcp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SaveMCPServerResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMcp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SaveMCPServerResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SaveMCPServerResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonResp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CommonResp == nil {
				m.CommonResp = &grpcep.CommonResp{}
			}
			if err := m.CommonResp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Server", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Server == nil {
				m.Server = &AgentMCPServer{}
			}
			if err := m.Server.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMcp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMcp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteMCPServerReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMcp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteMCPServerReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteMCPServerReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMcp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMcp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteMCPServerResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMcp
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteMCPServerResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteMCPServerResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommonResp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CommonResp == nil {
				m.CommonResp = &grpcep.CommonResp{}
			}
			if err := m.CommonResp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMcp
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMcp
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMcp(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMcp
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMcp(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMcp
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMcp
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMcp
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMcp
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMcp
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMcp        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMcp          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMcp = fmt.Errorf("proto: unexpected end of group")
)
