export function injectStyles() {
  if (document.getElementById('ga-book-styles')) return
  var style = document.createElement('style')
  style.id = 'ga-book-styles'
  style.textContent = getStyles()
  document.head.appendChild(style)
}

function getStyles() {
  return [
    '.ga-book-root{width:100%;min-height:100%;box-sizing:border-box;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;color:#1f2937;position:relative;}',
    '.ga-book-view{padding:20px 24px;}',
    '.ga-book-header{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin-bottom:16px;}',
    '.ga-book-title{margin:0;font-size:20px;font-weight:600;color:#111827;}',
    '.ga-book-desc{margin:4px 0 0;font-size:13px;color:#6b7280;}',
    '.ga-book-header-actions{display:flex;gap:8px;align-items:center;flex-shrink:0;}',
    '.ga-book-toolbar{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:16px;align-items:center;}',
    '.ga-book-search{min-width:200px;padding:8px 12px;border:1px solid #e5e7eb;border-radius:6px;font-size:14px;outline:none;box-sizing:border-box;font-family:inherit;}',
    '.ga-book-search:focus{border-color:#1677ff;box-shadow:0 0 0 2px rgba(22,119,255,0.1);}',
    '.ga-book-select{min-width:140px;padding:8px 12px;border:1px solid #e5e7eb;border-radius:6px;font-size:14px;outline:none;background:white;box-sizing:border-box;font-family:inherit;}',
    '.ga-book-select:focus{border-color:#1677ff;box-shadow:0 0 0 2px rgba(22,119,255,0.1);}',
    '.ga-book-btn{display:inline-flex;align-items:center;justify-content:center;padding:8px 14px;font-size:14px;border-radius:6px;border:1px solid transparent;cursor:pointer;white-space:nowrap;transition:background 0.15s,border-color 0.15s,opacity 0.15s;font-family:inherit;line-height:1.4;}',
    '.ga-book-btn-primary{background:#1677ff;color:white;border-color:transparent;}',
    '.ga-book-btn-primary:hover{background:#4096ff;}',
    '.ga-book-btn-primary:disabled{opacity:0.5;cursor:not-allowed;}',
    '.ga-book-btn-secondary{background:white;color:#1f2937;border-color:#e5e7eb;}',
    '.ga-book-btn-secondary:hover{background:#f3f4f6;}',
    '.ga-book-btn-clear{background:white;color:#6b7280;border:1px solid #e5e7eb;border-radius:6px;font-size:14px;padding:8px 14px;cursor:pointer;font-family:inherit;}',
    '.ga-book-btn-clear:hover{background:#f3f4f6;color:#1f2937;}',
    '.ga-book-btn-danger{background:white;color:#dc2626;border:1px solid transparent;padding:8px 14px;font-size:14px;border-radius:6px;cursor:pointer;font-family:inherit;}',
    '.ga-book-btn-danger:hover{background:#fef2f2;}',
    '.ga-book-btn-danger:disabled{opacity:0.5;cursor:not-allowed;}',
    '.ga-book-btn-small{padding:4px 10px;font-size:13px;background:white;color:#1f2937;border:1px solid #e5e7eb;border-radius:6px;cursor:pointer;font-family:inherit;line-height:1.4;}',
    '.ga-book-btn-small:hover{background:#f3f4f6;}',
    '.ga-book-btn-small:disabled{opacity:0.5;cursor:not-allowed;}',
    '.ga-book-btn-small-danger{padding:4px 10px;font-size:13px;background:white;color:#dc2626;border:1px solid transparent;border-radius:6px;cursor:pointer;font-family:inherit;line-height:1.4;}',
    '.ga-book-btn-small-danger:hover{background:#fef2f2;}',
    '.ga-book-table-wrapper{border:1px solid #e5e7eb;border-radius:8px;overflow-x:auto;}',
    '.ga-book-table{width:100%;border-collapse:collapse;}',
    '.ga-book-table th{background:#f9fafb;font-size:13px;font-weight:600;color:#6b7280;padding:10px 14px;text-align:left;white-space:nowrap;}',
    '.ga-book-table td{font-size:14px;padding:10px 14px;border-top:1px solid #f3f4f6;}',
    '.ga-book-table tbody tr:hover{background:#f9fafb;}',
    '.ga-book-cell-title{max-width:220px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}',
    '.ga-book-actions{white-space:nowrap;display:flex;gap:4px;justify-content:flex-end;}',
    '.ga-book-actions-th{text-align:right;}',
    '.ga-book-badge{display:inline-block;padding:2px 8px;font-size:12px;font-weight:500;border-radius:10px;line-height:1.6;}',
    '.ga-book-badge-onshelf{background:#ecfdf5;color:#059669;}',
    '.ga-book-badge-lent{background:#eff6ff;color:#2563eb;}',
    '.ga-book-badge-offshelf{background:#f3f4f6;color:#6b7280;}',
    '.ga-book-pagination{display:flex;justify-content:space-between;align-items:center;margin-top:12px;font-size:13px;color:#6b7280;}',
    '.ga-book-page-info{color:#6b7280;}',
    '.ga-book-page-btns{display:flex;gap:4px;align-items:center;}',
    '.ga-book-page-btn{min-width:32px;height:32px;padding:0 6px;border:1px solid #e5e7eb;border-radius:6px;background:white;color:#1f2937;font-size:13px;cursor:pointer;text-align:center;font-family:inherit;}',
    '.ga-book-page-btn:hover{background:#f3f4f6;border-color:#d1d5db;}',
    '.ga-book-page-active{background:#1677ff;color:white;border-color:#1677ff;}',
    '.ga-book-page-active:hover{background:#4096ff;}',
    '.ga-book-page-ellipsis{padding:0 4px;color:#9ca3af;}',
    '.ga-book-modal-mask{position:absolute;inset:0;background:rgba(0,0,0,0.45);z-index:1000;display:flex;align-items:center;justify-content:center;}',
    '.ga-book-modal{background:white;border-radius:8px;box-shadow:0 18px 45px rgba(15,23,42,0.16);max-width:calc(100vw - 32px);max-height:calc(100vh - 64px);overflow-y:auto;box-sizing:border-box;}',
    '.ga-book-modal-header{display:flex;justify-content:space-between;align-items:center;padding:16px 20px 0;}',
    '.ga-book-modal-title{font-size:16px;font-weight:600;color:#111827;}',
    '.ga-book-modal-close{background:none;border:none;font-size:20px;color:#9ca3af;cursor:pointer;padding:0;line-height:1;}',
    '.ga-book-modal-close:hover{color:#6b7280;}',
    '.ga-book-modal-body{padding:16px 20px;}',
    '.ga-book-modal-footer{display:flex;justify-content:flex-end;gap:8px;padding:12px 20px 16px;}',
    '.ga-book-modal-error{padding:8px 12px;background:#fef2f2;color:#dc2626;font-size:12px;border-radius:6px;margin-bottom:12px;}',
    '.ga-book-drawer-mask{position:absolute;inset:0;background:rgba(0,0,0,0.2);z-index:1000;display:flex;justify-content:flex-end;}',
    '.ga-book-drawer{width:440px;max-width:calc(100vw - 32px);height:100%;background:white;border-radius:8px 0 0 8px;box-shadow:0 18px 45px rgba(15,23,42,0.16);overflow-y:auto;display:flex;flex-direction:column;box-sizing:border-box;}',
    '.ga-book-drawer-header{display:flex;justify-content:space-between;align-items:center;padding:16px 20px;border-bottom:1px solid #f3f4f6;}',
    '.ga-book-drawer-title{font-size:16px;font-weight:600;color:#111827;}',
    '.ga-book-drawer-close{background:none;border:none;font-size:20px;color:#9ca3af;cursor:pointer;padding:0;line-height:1;}',
    '.ga-book-drawer-close:hover{color:#6b7280;}',
    '.ga-book-drawer-body{padding:16px 20px;flex:1;overflow-y:auto;}',
    '.ga-book-drawer-footer{padding:12px 20px 16px;border-top:1px solid #f3f4f6;display:flex;gap:8px;flex-wrap:wrap;}',
    '.ga-book-detail-field{display:flex;padding:8px 0;border-bottom:1px solid #f9fafb;}',
    '.ga-book-detail-label{width:88px;flex-shrink:0;font-size:13px;color:#6b7280;font-weight:500;}',
    '.ga-book-detail-value{font-size:14px;color:#1f2937;word-break:break-all;}',
    '.ga-book-form-section{margin-bottom:16px;}',
    '.ga-book-form-section-title{font-size:13px;font-weight:600;color:#6b7280;margin-bottom:8px;padding-bottom:4px;border-bottom:1px solid #f3f4f6;}',
    '.ga-book-form-field{margin-bottom:12px;}',
    '.ga-book-form-label{display:block;font-size:14px;font-weight:500;color:#1f2937;margin-bottom:4px;}',
    '.ga-book-required{color:#dc2626;margin-right:2px;}',
    '.ga-book-input{width:100%;padding:8px 12px;border:1px solid #e5e7eb;border-radius:6px;font-size:14px;outline:none;box-sizing:border-box;font-family:inherit;}',
    '.ga-book-input:focus{border-color:#1677ff;box-shadow:0 0 0 2px rgba(22,119,255,0.1);}',
    '.ga-book-input-error{border-color:#dc2626;}',
    '.ga-book-input-error:focus{border-color:#dc2626;box-shadow:0 0 0 2px rgba(220,38,38,0.1);}',
    '.ga-book-field-error{font-size:12px;color:#dc2626;margin-top:4px;}',
    '.ga-book-readonly-value{font-size:14px;color:#1f2937;padding:8px 12px;background:#f9fafb;border-radius:6px;border:1px solid #f3f4f6;}',
    '.ga-book-qty-book{font-size:14px;color:#1f2937;padding:8px 12px;background:#f9fafb;border-radius:6px;border:1px solid #f3f4f6;}',
    '.ga-book-toast-container{position:absolute;top:16px;right:16px;z-index:2000;display:flex;flex-direction:column;gap:8px;}',
    '.ga-book-toast{padding:10px 16px;border-radius:8px;font-size:13px;box-shadow:0 18px 45px rgba(15,23,42,0.16);background:white;transition:all 0.3s;}',
    '.ga-book-toast-success{border-left:4px solid #059669;}',
    '.ga-book-toast-error{border-left:4px solid #dc2626;}',
    '.ga-book-loading{padding:40px 20px;}',
    '.ga-book-skeleton-row{padding:10px 0;}',
    '.ga-book-skeleton{height:14px;background:#f3f4f6;border-radius:4px;animation:ga-book-pulse 1.5s ease-in-out infinite;}',
    '@keyframes ga-book-pulse{0%,100%{opacity:1;}50%{opacity:0.5;}}',
    '.ga-book-empty{padding:60px 20px;text-align:center;color:#6b7280;font-size:14px;}',
    '.ga-book-error{padding:60px 20px;text-align:center;color:#dc2626;font-size:14px;}',
    '.ga-book-confirm-message{font-size:14px;color:#1f2937;line-height:1.6;margin:0;}',
    '@media(max-width:720px){',
    '.ga-book-header{flex-direction:column;align-items:flex-start;}',
    '.ga-book-toolbar>input,.ga-book-toolbar>select{width:100%;min-width:0;}',
    '.ga-book-table-wrapper{overflow-x:auto;}',
    '.ga-book-modal{width:calc(100vw - 32px) !important;}',
    '.ga-book-drawer{width:calc(100vw - 32px);}',
    '.ga-book-actions{flex-wrap:wrap;}',
    '}',
  ].join('')
}
